// flow-typed signature: 8f349a8d312c6bd966c50bfef534f6c1
// flow-typed version: <<STUB>>/@atomic-reactor/gulp-watch_v^5.0.1-patched/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atomic-reactor/gulp-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atomic-reactor/gulp-watch' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@atomic-reactor/gulp-watch/index' {
    declare module.exports: $Exports<'@atomic-reactor/gulp-watch'>;
}
declare module '@atomic-reactor/gulp-watch/index.js' {
    declare module.exports: $Exports<'@atomic-reactor/gulp-watch'>;
}
