// flow-typed signature: 5088f1d65430007c24a3763a7dd30b0c
// flow-typed version: <<STUB>>/@atomic-reactor/reactium-sdk-core_v0.0.18/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atomic-reactor/reactium-sdk-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atomic-reactor/reactium-sdk-core' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atomic-reactor/reactium-sdk-core/lib/cache' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/component' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/enums' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/handle' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/hook' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/component' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/derived-state' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/handle' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/redux' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/plugin' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/prefs' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/pulse/enums' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/pulse' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/utils' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/zone' {
    declare module.exports: any;
}

declare module '@atomic-reactor/reactium-sdk-core/lib/zone/Zone' {
    declare module.exports: any;
}

// Filename aliases
declare module '@atomic-reactor/reactium-sdk-core/lib/cache/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/cache',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/cache/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/cache',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/component/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/component',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/component/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/component',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/enums.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/enums',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/handle/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/handle',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/handle/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/handle',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/hook/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/hook',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/hook/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/hook',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/index' {
    declare module.exports: $Exports<'@atomic-reactor/reactium-sdk-core/lib'>;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/index.js' {
    declare module.exports: $Exports<'@atomic-reactor/reactium-sdk-core/lib'>;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/component.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/named-exports/component',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/derived-state.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/named-exports/derived-state',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/handle.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/named-exports/handle',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/named-exports',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/named-exports',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/named-exports/redux.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/named-exports/redux',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/plugin/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/plugin',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/plugin/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/plugin',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/prefs/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/prefs',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/prefs/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/prefs',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/pulse/enums.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/pulse/enums',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/pulse/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/pulse',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/pulse/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/pulse',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/utils/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/utils',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/utils/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/utils',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/zone/index' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/zone',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/zone/index.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/zone',
    >;
}
declare module '@atomic-reactor/reactium-sdk-core/lib/zone/Zone.js' {
    declare module.exports: $Exports<
        '@atomic-reactor/reactium-sdk-core/lib/zone/Zone',
    >;
}
