// flow-typed signature: 48f55b766498262290ae94bf8e51179d
// flow-typed version: <<STUB>>/@atomic-reactor/webpack-po-loader_v0.0.3/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atomic-reactor/webpack-po-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atomic-reactor/webpack-po-loader' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@atomic-reactor/webpack-po-loader/index' {
    declare module.exports: $Exports<'@atomic-reactor/webpack-po-loader'>;
}
declare module '@atomic-reactor/webpack-po-loader/index.js' {
    declare module.exports: $Exports<'@atomic-reactor/webpack-po-loader'>;
}
