const tree = require('directory-tree');
const path = require('path');
const fs   = require('fs');

const flattenRegistry =
    (registry = {children: []}, manifest = []) => registry.children
        .reduce((manifest, item) => {
            if ( 'children' in item ) {
                return flattenRegistry(item, manifest);
            }
            if ( 'path' in item ) {
                manifest.push(item);
            }
            return manifest;
        }, manifest);

const jsSources = sourcePath => flattenRegistry(tree(sourcePath, {
    extensions: /\.js$/,
    exclude: /.ds_store/i
}));

const find = (searches = [], sourcePath) => {
    const mappings = searches.reduce((mappings, {name}) => {
        mappings[name] = [];
        return mappings;
    }, {});

    return jsSources(sourcePath)
        .map(file => file.path)
        .reduce((mappings, file) => {
            searches.forEach(({name, pattern}) => {
                if ( pattern.test(file) ) {
                    mappings[name].push(file.replace(/src\/app\//, '').replace(/.js$/, ''));
                }
            })

            return mappings;
        }, mappings);
}

const manifest = find([
    {
        name: 'entries',
        pattern: /^src\/app\/\w+?\.js$/,
    },
    {
        name: 'allActions',
        pattern: /actions.js$/,
    },
    {
        name: 'allActionTypes',
        pattern: /actionTypes.js$/,
    },
    {
        name: 'allReducers',
        pattern: /reducers.js$/,
    },
    {
        name: 'allInitialStates',
        pattern: /state.js$/,
    },
    {
        name: 'allRoutes',
        pattern: /route.js$/,
    },
    {
        name: 'allServices',
        pattern: /services.js$/,
    },
], './src/app');

fs.writeFileSync(path.resolve('./src/', 'manifest.js'), `
/** generated by createManifest.js **/
module.exports = ${JSON.stringify(manifest, null, 2)};
`);
