// flow-typed signature: 004595f922791c45a556c20f3fa6780c
// flow-typed version: <<STUB>>/@loadable/component_v^5.11.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@loadable/component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@loadable/component' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@loadable/component/dist/loadable.cjs' {
    declare module.exports: any;
}

declare module '@loadable/component/dist/loadable.esm' {
    declare module.exports: any;
}

declare module '@loadable/component/dist/loadable' {
    declare module.exports: any;
}

declare module '@loadable/component/dist/loadable.min' {
    declare module.exports: any;
}

// Filename aliases
declare module '@loadable/component/dist/loadable.cjs.js' {
    declare module.exports: $Exports<'@loadable/component/dist/loadable.cjs'>;
}
declare module '@loadable/component/dist/loadable.esm.js' {
    declare module.exports: $Exports<'@loadable/component/dist/loadable.esm'>;
}
declare module '@loadable/component/dist/loadable.js' {
    declare module.exports: $Exports<'@loadable/component/dist/loadable'>;
}
declare module '@loadable/component/dist/loadable.min.js' {
    declare module.exports: $Exports<'@loadable/component/dist/loadable.min'>;
}
