// flow-typed signature: 74869d3ebae894137e4618c0091d847d
// flow-typed version: <<STUB>>/action-sequence_v^1.1.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'action-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'action-sequence' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'action-sequence/test/spec' {
    declare module.exports: any;
}

// Filename aliases
declare module 'action-sequence/index' {
    declare module.exports: $Exports<'action-sequence'>;
}
declare module 'action-sequence/index.js' {
    declare module.exports: $Exports<'action-sequence'>;
}
declare module 'action-sequence/test/spec.js' {
    declare module.exports: $Exports<'action-sequence/test/spec'>;
}
