// flow-typed signature: ef54ba39592df836c2103b519f88872e
// flow-typed version: <<STUB>>/apidoc_v^0.19.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apidoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apidoc' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apidoc/example/_apidoc' {
    declare module.exports: any;
}

declare module 'apidoc/example/example' {
    declare module.exports: any;
}

declare module 'apidoc/lib' {
    declare module.exports: any;
}

declare module 'apidoc/lib/package_info' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/ca' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/cs' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/de' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/es' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/fr' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/it' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/locale' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/nl' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/pl' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/pt_br' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/ro' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/ru' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/tr' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/vi' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/zh_cn' {
    declare module.exports: any;
}

declare module 'apidoc/template/locales/zh' {
    declare module.exports: any;
}

declare module 'apidoc/template/main' {
    declare module.exports: any;
}

declare module 'apidoc/template/utils/handlebars_helper' {
    declare module.exports: any;
}

declare module 'apidoc/template/utils/send_sample_request' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/bootstrap.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/diff_match_patch.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/handlebars.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/jquery.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/list.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/lodash.custom.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/path-to-regexp' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/polyfill' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-aea' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-agc' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-apollo' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-basic' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-cbm' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-cl' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-clj' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-css' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-dart' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-el' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-erl' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-erlang' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-fs' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-go' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-hs' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-lasso' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-lassoscript' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-latex' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-lgt' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-lisp' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-ll' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-llvm' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-logtalk' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-ls' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-lsp' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-lua' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-matlab' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-ml' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-mumps' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-n' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-nemerle' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-pascal' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-proto' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-r' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-rd' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-rkt' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-rust' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-s' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-scala' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-scm' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-Splus' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-sql' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-ss' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-swift' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-tcl' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-tex' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-vb' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-vbs' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-vhd' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-vhdl' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-wiki' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-xq' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-xquery' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-yaml' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/lang-yml' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/prettify' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/prettify/run_prettify' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/require.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/semver.min' {
    declare module.exports: any;
}

declare module 'apidoc/template/vendor/webfontloader' {
    declare module.exports: any;
}

// Filename aliases
declare module 'apidoc/example/_apidoc.js' {
    declare module.exports: $Exports<'apidoc/example/_apidoc'>;
}
declare module 'apidoc/example/example.js' {
    declare module.exports: $Exports<'apidoc/example/example'>;
}
declare module 'apidoc/lib/index' {
    declare module.exports: $Exports<'apidoc/lib'>;
}
declare module 'apidoc/lib/index.js' {
    declare module.exports: $Exports<'apidoc/lib'>;
}
declare module 'apidoc/lib/package_info.js' {
    declare module.exports: $Exports<'apidoc/lib/package_info'>;
}
declare module 'apidoc/template/locales/ca.js' {
    declare module.exports: $Exports<'apidoc/template/locales/ca'>;
}
declare module 'apidoc/template/locales/cs.js' {
    declare module.exports: $Exports<'apidoc/template/locales/cs'>;
}
declare module 'apidoc/template/locales/de.js' {
    declare module.exports: $Exports<'apidoc/template/locales/de'>;
}
declare module 'apidoc/template/locales/es.js' {
    declare module.exports: $Exports<'apidoc/template/locales/es'>;
}
declare module 'apidoc/template/locales/fr.js' {
    declare module.exports: $Exports<'apidoc/template/locales/fr'>;
}
declare module 'apidoc/template/locales/it.js' {
    declare module.exports: $Exports<'apidoc/template/locales/it'>;
}
declare module 'apidoc/template/locales/locale.js' {
    declare module.exports: $Exports<'apidoc/template/locales/locale'>;
}
declare module 'apidoc/template/locales/nl.js' {
    declare module.exports: $Exports<'apidoc/template/locales/nl'>;
}
declare module 'apidoc/template/locales/pl.js' {
    declare module.exports: $Exports<'apidoc/template/locales/pl'>;
}
declare module 'apidoc/template/locales/pt_br.js' {
    declare module.exports: $Exports<'apidoc/template/locales/pt_br'>;
}
declare module 'apidoc/template/locales/ro.js' {
    declare module.exports: $Exports<'apidoc/template/locales/ro'>;
}
declare module 'apidoc/template/locales/ru.js' {
    declare module.exports: $Exports<'apidoc/template/locales/ru'>;
}
declare module 'apidoc/template/locales/tr.js' {
    declare module.exports: $Exports<'apidoc/template/locales/tr'>;
}
declare module 'apidoc/template/locales/vi.js' {
    declare module.exports: $Exports<'apidoc/template/locales/vi'>;
}
declare module 'apidoc/template/locales/zh_cn.js' {
    declare module.exports: $Exports<'apidoc/template/locales/zh_cn'>;
}
declare module 'apidoc/template/locales/zh.js' {
    declare module.exports: $Exports<'apidoc/template/locales/zh'>;
}
declare module 'apidoc/template/main.js' {
    declare module.exports: $Exports<'apidoc/template/main'>;
}
declare module 'apidoc/template/utils/handlebars_helper.js' {
    declare module.exports: $Exports<'apidoc/template/utils/handlebars_helper'>;
}
declare module 'apidoc/template/utils/send_sample_request.js' {
    declare module.exports: $Exports<
        'apidoc/template/utils/send_sample_request',
    >;
}
declare module 'apidoc/template/vendor/bootstrap.min.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/bootstrap.min'>;
}
declare module 'apidoc/template/vendor/diff_match_patch.min.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/diff_match_patch.min',
    >;
}
declare module 'apidoc/template/vendor/handlebars.min.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/handlebars.min'>;
}
declare module 'apidoc/template/vendor/jquery.min.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/jquery.min'>;
}
declare module 'apidoc/template/vendor/list.min.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/list.min'>;
}
declare module 'apidoc/template/vendor/lodash.custom.min.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/lodash.custom.min',
    >;
}
declare module 'apidoc/template/vendor/path-to-regexp/index' {
    declare module.exports: $Exports<'apidoc/template/vendor/path-to-regexp'>;
}
declare module 'apidoc/template/vendor/path-to-regexp/index.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/path-to-regexp'>;
}
declare module 'apidoc/template/vendor/polyfill.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/polyfill'>;
}
declare module 'apidoc/template/vendor/prettify/lang-aea.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-aea',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-agc.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-agc',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-apollo.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-apollo',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-basic.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-basic',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-cbm.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-cbm',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-cl.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-cl'>;
}
declare module 'apidoc/template/vendor/prettify/lang-clj.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-clj',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-css.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-css',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-dart.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-dart',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-el.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-el'>;
}
declare module 'apidoc/template/vendor/prettify/lang-erl.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-erl',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-erlang.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-erlang',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-fs.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-fs'>;
}
declare module 'apidoc/template/vendor/prettify/lang-go.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-go'>;
}
declare module 'apidoc/template/vendor/prettify/lang-hs.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-hs'>;
}
declare module 'apidoc/template/vendor/prettify/lang-lasso.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-lasso',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-lassoscript.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-lassoscript',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-latex.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-latex',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-lgt.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-lgt',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-lisp.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-lisp',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-ll.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-ll'>;
}
declare module 'apidoc/template/vendor/prettify/lang-llvm.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-llvm',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-logtalk.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-logtalk',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-ls.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-ls'>;
}
declare module 'apidoc/template/vendor/prettify/lang-lsp.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-lsp',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-lua.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-lua',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-matlab.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-matlab',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-ml.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-ml'>;
}
declare module 'apidoc/template/vendor/prettify/lang-mumps.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-mumps',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-n.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-n'>;
}
declare module 'apidoc/template/vendor/prettify/lang-nemerle.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-nemerle',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-pascal.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-pascal',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-proto.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-proto',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-r.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-r'>;
}
declare module 'apidoc/template/vendor/prettify/lang-rd.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-rd'>;
}
declare module 'apidoc/template/vendor/prettify/lang-rkt.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-rkt',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-rust.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-rust',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-s.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-s'>;
}
declare module 'apidoc/template/vendor/prettify/lang-scala.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-scala',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-scm.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-scm',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-Splus.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-Splus',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-sql.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-sql',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-ss.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-ss'>;
}
declare module 'apidoc/template/vendor/prettify/lang-swift.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-swift',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-tcl.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-tcl',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-tex.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-tex',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-vb.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-vb'>;
}
declare module 'apidoc/template/vendor/prettify/lang-vbs.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-vbs',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-vhd.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-vhd',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-vhdl.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-vhdl',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-wiki.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-wiki',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-xq.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/prettify/lang-xq'>;
}
declare module 'apidoc/template/vendor/prettify/lang-xquery.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-xquery',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-yaml.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-yaml',
    >;
}
declare module 'apidoc/template/vendor/prettify/lang-yml.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/lang-yml',
    >;
}
declare module 'apidoc/template/vendor/prettify/prettify.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/prettify',
    >;
}
declare module 'apidoc/template/vendor/prettify/run_prettify.js' {
    declare module.exports: $Exports<
        'apidoc/template/vendor/prettify/run_prettify',
    >;
}
declare module 'apidoc/template/vendor/require.min.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/require.min'>;
}
declare module 'apidoc/template/vendor/semver.min.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/semver.min'>;
}
declare module 'apidoc/template/vendor/webfontloader.js' {
    declare module.exports: $Exports<'apidoc/template/vendor/webfontloader'>;
}
