// flow-typed signature: 3eab025c9743b84de9ae571592ee1535
// flow-typed version: <<STUB>>/atomic-reactor-cli_v^2.1.19/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atomic-reactor-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atomic-reactor-cli' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atomic-reactor-cli/arcli' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/install/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/install/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/install' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/update/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/update/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/update' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/actinium/update/package' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/cli/command/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/cli/command/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/cli/command' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/config/set/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/config/set/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/config/set' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/label' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/empty/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/empty/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/empty' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/install/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/install/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/install' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/update/actions' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/update/generator' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/update' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/update/package' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/update/template/babel.config' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/commands/reactium/update/template/gulpfile' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/lib/listItem' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/lib/messenger' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/lib/pad' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/postinstall' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/test/config-set.spec' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/test/reactium-install.spec' {
    declare module.exports: any;
}

declare module 'atomic-reactor-cli/test/reactium-update.spec' {
    declare module.exports: any;
}

// Filename aliases
declare module 'atomic-reactor-cli/arcli.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/arcli'>;
}
declare module 'atomic-reactor-cli/commands/actinium/index' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/actinium'>;
}
declare module 'atomic-reactor-cli/commands/actinium/index.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/actinium'>;
}
declare module 'atomic-reactor-cli/commands/actinium/install/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/install/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/install/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/install/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/install/index' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/install',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/install/index.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/install',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/update/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/update/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/update/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/update/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/update/index' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/update',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/update/index.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/update',
    >;
}
declare module 'atomic-reactor-cli/commands/actinium/update/package.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/actinium/update/package',
    >;
}
declare module 'atomic-reactor-cli/commands/cli/command/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/cli/command/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/cli/command/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/cli/command/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/cli/command/index' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/cli/command'>;
}
declare module 'atomic-reactor-cli/commands/cli/command/index.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/cli/command'>;
}
declare module 'atomic-reactor-cli/commands/config/set/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/config/set/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/config/set/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/config/set/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/config/set/index' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/config/set'>;
}
declare module 'atomic-reactor-cli/commands/config/set/index.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/config/set'>;
}
declare module 'atomic-reactor-cli/commands/label/index' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/label'>;
}
declare module 'atomic-reactor-cli/commands/label/index.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/label'>;
}
declare module 'atomic-reactor-cli/commands/reactium/empty/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/empty/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/empty/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/empty/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/empty/index' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/empty',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/empty/index.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/empty',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/index' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/reactium'>;
}
declare module 'atomic-reactor-cli/commands/reactium/index.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/commands/reactium'>;
}
declare module 'atomic-reactor-cli/commands/reactium/install/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/install/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/install/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/install/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/install/index' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/install',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/install/index.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/install',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/actions.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update/actions',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/generator.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update/generator',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/index' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/index.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/package.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update/package',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/template/babel.config.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update/template/babel.config',
    >;
}
declare module 'atomic-reactor-cli/commands/reactium/update/template/gulpfile.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/commands/reactium/update/template/gulpfile',
    >;
}
declare module 'atomic-reactor-cli/lib/listItem.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/lib/listItem'>;
}
declare module 'atomic-reactor-cli/lib/messenger.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/lib/messenger'>;
}
declare module 'atomic-reactor-cli/lib/pad.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/lib/pad'>;
}
declare module 'atomic-reactor-cli/postinstall.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/postinstall'>;
}
declare module 'atomic-reactor-cli/test/config-set.spec.js' {
    declare module.exports: $Exports<'atomic-reactor-cli/test/config-set.spec'>;
}
declare module 'atomic-reactor-cli/test/reactium-install.spec.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/test/reactium-install.spec',
    >;
}
declare module 'atomic-reactor-cli/test/reactium-update.spec.js' {
    declare module.exports: $Exports<
        'atomic-reactor-cli/test/reactium-update.spec',
    >;
}
