// flow-typed signature: af445ef2fe1325e38559747f6e76cbae
// flow-typed version: <<STUB>>/cli-spinners_v^2.2.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cli-spinners'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cli-spinners' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'cli-spinners/index' {
    declare module.exports: $Exports<'cli-spinners'>;
}
declare module 'cli-spinners/index.js' {
    declare module.exports: $Exports<'cli-spinners'>;
}
