// flow-typed signature: f2264065ff45eab48a93d10aa5680149
// flow-typed version: <<STUB>>/decamelize_v^3.2.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decamelize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decamelize' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'decamelize/index' {
    declare module.exports: $Exports<'decamelize'>;
}
declare module 'decamelize/index.js' {
    declare module.exports: $Exports<'decamelize'>;
}
