// flow-typed signature: f51591e96454dcdbd552163468c8af74
// flow-typed version: <<STUB>>/express-static-gzip_v^2.0.5/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-static-gzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-static-gzip' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-static-gzip/test/e2e.spec' {
    declare module.exports: any;
}

declare module 'express-static-gzip/test/encoding-selection.spec' {
    declare module.exports: any;
}

declare module 'express-static-gzip/test/options.spec' {
    declare module.exports: any;
}

declare module 'express-static-gzip/test/wwwroot/main' {
    declare module.exports: any;
}

declare module 'express-static-gzip/util/encoding-selection' {
    declare module.exports: any;
}

declare module 'express-static-gzip/util/options' {
    declare module.exports: any;
}

// Filename aliases
declare module 'express-static-gzip/index' {
    declare module.exports: $Exports<'express-static-gzip'>;
}
declare module 'express-static-gzip/index.js' {
    declare module.exports: $Exports<'express-static-gzip'>;
}
declare module 'express-static-gzip/test/e2e.spec.js' {
    declare module.exports: $Exports<'express-static-gzip/test/e2e.spec'>;
}
declare module 'express-static-gzip/test/encoding-selection.spec.js' {
    declare module.exports: $Exports<
        'express-static-gzip/test/encoding-selection.spec',
    >;
}
declare module 'express-static-gzip/test/options.spec.js' {
    declare module.exports: $Exports<'express-static-gzip/test/options.spec'>;
}
declare module 'express-static-gzip/test/wwwroot/main.js' {
    declare module.exports: $Exports<'express-static-gzip/test/wwwroot/main'>;
}
declare module 'express-static-gzip/util/encoding-selection.js' {
    declare module.exports: $Exports<
        'express-static-gzip/util/encoding-selection',
    >;
}
declare module 'express-static-gzip/util/options.js' {
    declare module.exports: $Exports<'express-static-gzip/util/options'>;
}
