// flow-typed signature: 4c1f4d5901d3bf23ee1ff3876985b55e
// flow-typed version: <<STUB>>/fast-diff_v^1.2.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-diff' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-diff/diff' {
    declare module.exports: any;
}

declare module 'fast-diff/test' {
    declare module.exports: any;
}

// Filename aliases
declare module 'fast-diff/diff.js' {
    declare module.exports: $Exports<'fast-diff/diff'>;
}
declare module 'fast-diff/test.js' {
    declare module.exports: $Exports<'fast-diff/test'>;
}
