// flow-typed signature: cc4044400c02dee469c6c77434bfc3e5
// flow-typed version: <<STUB>>/file-api_v^0.10.4/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-api' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'file-api/index' {
    declare module.exports: $Exports<'file-api'>;
}
declare module 'file-api/index.js' {
    declare module.exports: $Exports<'file-api'>;
}
