// flow-typed signature: c52f19a84365e1a0454999c9d1df7692
// flow-typed version: <<STUB>>/fs-readdir-recursive_v^1.1.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-readdir-recursive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-readdir-recursive' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'fs-readdir-recursive/index' {
    declare module.exports: $Exports<'fs-readdir-recursive'>;
}
declare module 'fs-readdir-recursive/index.js' {
    declare module.exports: $Exports<'fs-readdir-recursive'>;
}
