// flow-typed signature: 419f806d8e8761ae33ab9fe241abb223
// flow-typed version: <<STUB>>/gettext-extract_v^2.0.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gettext-extract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gettext-extract' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gettext-extract/index' {
    declare module.exports: $Exports<'gettext-extract'>;
}
declare module 'gettext-extract/index.js' {
    declare module.exports: $Exports<'gettext-extract'>;
}
