// flow-typed signature: a8d35863262b459c550fc52f8a3e7dac
// flow-typed version: <<STUB>>/gulp-run_v^1.7.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-run' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-run/command' {
    declare module.exports: any;
}

declare module 'gulp-run/gulpfile' {
    declare module.exports: any;
}

declare module 'gulp-run/test/command.test' {
    declare module.exports: any;
}

declare module 'gulp-run/test/index.test' {
    declare module.exports: any;
}

declare module 'gulp-run/test/util' {
    declare module.exports: any;
}

// Filename aliases
declare module 'gulp-run/command.js' {
    declare module.exports: $Exports<'gulp-run/command'>;
}
declare module 'gulp-run/gulpfile.js' {
    declare module.exports: $Exports<'gulp-run/gulpfile'>;
}
declare module 'gulp-run/index' {
    declare module.exports: $Exports<'gulp-run'>;
}
declare module 'gulp-run/index.js' {
    declare module.exports: $Exports<'gulp-run'>;
}
declare module 'gulp-run/test/command.test.js' {
    declare module.exports: $Exports<'gulp-run/test/command.test'>;
}
declare module 'gulp-run/test/index.test.js' {
    declare module.exports: $Exports<'gulp-run/test/index.test'>;
}
declare module 'gulp-run/test/util.js' {
    declare module.exports: $Exports<'gulp-run/test/util'>;
}
