// flow-typed signature: 28e9b1b1577fdce084cb96dd261baafe
// flow-typed version: <<STUB>>/gulp-gzip_v^1.4.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-gzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-gzip' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-gzip/examples/advanced/gulpfile' {
    declare module.exports: any;
}

declare module 'gulp-gzip/examples/simple/gulpfile' {
    declare module.exports: any;
}

declare module 'gulp-gzip/gulpfile' {
    declare module.exports: any;
}

declare module 'gulp-gzip/lib/compress' {
    declare module.exports: any;
}

declare module 'gulp-gzip/lib/utils' {
    declare module.exports: any;
}

declare module 'gulp-gzip/test/test' {
    declare module.exports: any;
}

// Filename aliases
declare module 'gulp-gzip/examples/advanced/gulpfile.js' {
    declare module.exports: $Exports<'gulp-gzip/examples/advanced/gulpfile'>;
}
declare module 'gulp-gzip/examples/simple/gulpfile.js' {
    declare module.exports: $Exports<'gulp-gzip/examples/simple/gulpfile'>;
}
declare module 'gulp-gzip/gulpfile.js' {
    declare module.exports: $Exports<'gulp-gzip/gulpfile'>;
}
declare module 'gulp-gzip/index' {
    declare module.exports: $Exports<'gulp-gzip'>;
}
declare module 'gulp-gzip/index.js' {
    declare module.exports: $Exports<'gulp-gzip'>;
}
declare module 'gulp-gzip/lib/compress.js' {
    declare module.exports: $Exports<'gulp-gzip/lib/compress'>;
}
declare module 'gulp-gzip/lib/utils.js' {
    declare module.exports: $Exports<'gulp-gzip/lib/utils'>;
}
declare module 'gulp-gzip/test/test.js' {
    declare module.exports: $Exports<'gulp-gzip/test/test'>;
}
