// flow-typed signature: f4aaa5486a316434864828394224df2a
// flow-typed version: <<STUB>>/gulp-autoprefixer_v^7.0.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-autoprefixer' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp-autoprefixer/index' {
    declare module.exports: $Exports<'gulp-autoprefixer'>;
}
declare module 'gulp-autoprefixer/index.js' {
    declare module.exports: $Exports<'gulp-autoprefixer'>;
}
