// flow-typed signature: 3a48e8160449cda14940e5dfca4d93fb
// flow-typed version: <<STUB>>/gulp4-run-sequence_v^1.0.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp4-run-sequence'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp4-run-sequence' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp4-run-sequence/index' {
    declare module.exports: $Exports<'gulp4-run-sequence'>;
}
declare module 'gulp4-run-sequence/index.js' {
    declare module.exports: $Exports<'gulp4-run-sequence'>;
}
