// flow-typed signature: 8471ea7b68e40a78b07bfbd7b9fc7d74
// flow-typed version: <<STUB>>/gulp-sass_v^4.0.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sass' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'gulp-sass/index' {
    declare module.exports: $Exports<'gulp-sass'>;
}
declare module 'gulp-sass/index.js' {
    declare module.exports: $Exports<'gulp-sass'>;
}
