// flow-typed signature: 6a92230596a83cfc0d1538faefa6cfd8
// flow-typed version: <<STUB>>/jed_v^1.1.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jed' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jed/jed' {
    declare module.exports: any;
}

declare module 'jed/test/common' {
    declare module.exports: any;
}

declare module 'jed/test/jquery.min' {
    declare module.exports: any;
}

declare module 'jed/test/tests' {
    declare module.exports: any;
}

// Filename aliases
declare module 'jed/jed.js' {
    declare module.exports: $Exports<'jed/jed'>;
}
declare module 'jed/test/common.js' {
    declare module.exports: $Exports<'jed/test/common'>;
}
declare module 'jed/test/jquery.min.js' {
    declare module.exports: $Exports<'jed/test/jquery.min'>;
}
declare module 'jed/test/tests.js' {
    declare module.exports: $Exports<'jed/test/tests'>;
}
