// flow-typed signature: b7a361d0a7dec343e25f832b9ba4f2c9
// flow-typed version: <<STUB>>/module-alias_v^2.2.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'module-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'module-alias' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'module-alias/register' {
    declare module.exports: any;
}

// Filename aliases
declare module 'module-alias/index' {
    declare module.exports: $Exports<'module-alias'>;
}
declare module 'module-alias/index.js' {
    declare module.exports: $Exports<'module-alias'>;
}
declare module 'module-alias/register.js' {
    declare module.exports: $Exports<'module-alias/register'>;
}
