// flow-typed signature: b048ec35b25c414688f2d78112bfa5c1
// flow-typed version: <<STUB>>/node-sass-tilde-importer_v^1.0.2/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-tilde-importer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-tilde-importer' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'node-sass-tilde-importer/index' {
    declare module.exports: $Exports<'node-sass-tilde-importer'>;
}
declare module 'node-sass-tilde-importer/index.js' {
    declare module.exports: $Exports<'node-sass-tilde-importer'>;
}
