// flow-typed signature: d1fcfe2ad98b9cc64cdb65ac93d31623
// flow-typed version: <<STUB>>/node-sass-functions-json_v^1.0.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-functions-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-functions-json' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-sass-functions-json/dist' {
    declare module.exports: any;
}

declare module 'node-sass-functions-json/dist/lib/json-to-sass' {
    declare module.exports: any;
}

declare module 'node-sass-functions-json/dist/lib/sass-to-json' {
    declare module.exports: any;
}

// Filename aliases
declare module 'node-sass-functions-json/dist/index' {
    declare module.exports: $Exports<'node-sass-functions-json/dist'>;
}
declare module 'node-sass-functions-json/dist/index.js' {
    declare module.exports: $Exports<'node-sass-functions-json/dist'>;
}
declare module 'node-sass-functions-json/dist/lib/json-to-sass.js' {
    declare module.exports: $Exports<
        'node-sass-functions-json/dist/lib/json-to-sass',
    >;
}
declare module 'node-sass-functions-json/dist/lib/sass-to-json.js' {
    declare module.exports: $Exports<
        'node-sass-functions-json/dist/lib/sass-to-json',
    >;
}
