// flow-typed signature: e5ad5d825905a1b830f869bcd59bdbf4
// flow-typed version: <<STUB>>/parse_v^2.10.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse/dist/parse' {
    declare module.exports: any;
}

declare module 'parse/dist/parse.min' {
    declare module.exports: any;
}

declare module 'parse/dist/parse.weapp' {
    declare module.exports: any;
}

declare module 'parse/dist/parse.weapp.min' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Analytics' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/AnonymousUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/arrayContainsObject' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/canBeSerialized' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Cloud' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/CloudCode' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/CoreManager' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/decode' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/encode' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/equals' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/escape' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/EventEmitter' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/FacebookUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/InstallationController' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/isRevocableSession' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/LiveQueryClient' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/LiveQuerySubscription' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/LocalDatastore' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/LocalDatastoreController' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/LocalDatastoreController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/LocalDatastoreUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ObjectStateMutations' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/OfflineQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Parse' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseACL' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseConfig' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/parseDate' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseError' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseFile' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseGeoPoint' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseHooks' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseInstallation' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseLiveQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseObject' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseOp' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParsePolygon' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseRelation' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseRole' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseSchema' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseSession' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/ParseUser' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/promiseUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Push' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/RESTController' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/SingleInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Socket.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Storage' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.browser' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.default' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/StorageController.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/TaskQueue' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/unique' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/UniqueInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/unsavedChildren' {
    declare module.exports: any;
}

declare module 'parse/lib/browser/Xhr.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Analytics' {
    declare module.exports: any;
}

declare module 'parse/lib/node/AnonymousUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/node/arrayContainsObject' {
    declare module.exports: any;
}

declare module 'parse/lib/node/canBeSerialized' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Cloud' {
    declare module.exports: any;
}

declare module 'parse/lib/node/CloudCode' {
    declare module.exports: any;
}

declare module 'parse/lib/node/CoreManager' {
    declare module.exports: any;
}

declare module 'parse/lib/node/decode' {
    declare module.exports: any;
}

declare module 'parse/lib/node/encode' {
    declare module.exports: any;
}

declare module 'parse/lib/node/equals' {
    declare module.exports: any;
}

declare module 'parse/lib/node/escape' {
    declare module.exports: any;
}

declare module 'parse/lib/node/EventEmitter' {
    declare module.exports: any;
}

declare module 'parse/lib/node/FacebookUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/node/InstallationController' {
    declare module.exports: any;
}

declare module 'parse/lib/node/isRevocableSession' {
    declare module.exports: any;
}

declare module 'parse/lib/node/LiveQueryClient' {
    declare module.exports: any;
}

declare module 'parse/lib/node/LiveQuerySubscription' {
    declare module.exports: any;
}

declare module 'parse/lib/node/LocalDatastore' {
    declare module.exports: any;
}

declare module 'parse/lib/node/LocalDatastoreController' {
    declare module.exports: any;
}

declare module 'parse/lib/node/LocalDatastoreController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/node/LocalDatastoreUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ObjectStateMutations' {
    declare module.exports: any;
}

declare module 'parse/lib/node/OfflineQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Parse' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseACL' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseConfig' {
    declare module.exports: any;
}

declare module 'parse/lib/node/parseDate' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseError' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseFile' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseGeoPoint' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseHooks' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseInstallation' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseLiveQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseObject' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseOp' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParsePolygon' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseRelation' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseRole' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseSchema' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseSession' {
    declare module.exports: any;
}

declare module 'parse/lib/node/ParseUser' {
    declare module.exports: any;
}

declare module 'parse/lib/node/promiseUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Push' {
    declare module.exports: any;
}

declare module 'parse/lib/node/RESTController' {
    declare module.exports: any;
}

declare module 'parse/lib/node/SingleInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Socket.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Storage' {
    declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.browser' {
    declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.default' {
    declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/node/StorageController.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/node/TaskQueue' {
    declare module.exports: any;
}

declare module 'parse/lib/node/unique' {
    declare module.exports: any;
}

declare module 'parse/lib/node/UniqueInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/node/unsavedChildren' {
    declare module.exports: any;
}

declare module 'parse/lib/node/Xhr.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Analytics' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/AnonymousUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/arrayContainsObject' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/canBeSerialized' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Cloud' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/CloudCode' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/CoreManager' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/decode' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/encode' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/equals' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/escape' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/EventEmitter' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/FacebookUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/InstallationController' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/isRevocableSession' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/LiveQueryClient' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/LiveQuerySubscription' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/LocalDatastore' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/LocalDatastoreController' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/LocalDatastoreController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/LocalDatastoreUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ObjectStateMutations' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/OfflineQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Parse' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseACL' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseConfig' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/parseDate' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseError' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseFile' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseGeoPoint' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseHooks' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseInstallation' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseLiveQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseObject' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseOp' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParsePolygon' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseRelation' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseRole' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseSchema' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseSession' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/ParseUser' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/promiseUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Push' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/RESTController' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/SingleInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Socket.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Storage' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.browser' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.default' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/StorageController.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/TaskQueue' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/unique' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/UniqueInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/unsavedChildren' {
    declare module.exports: any;
}

declare module 'parse/lib/react-native/Xhr.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Analytics' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/AnonymousUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/arrayContainsObject' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/canBeSerialized' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Cloud' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/CloudCode' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/CoreManager' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/decode' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/encode' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/equals' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/escape' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/EventEmitter' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/FacebookUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/InstallationController' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/isRevocableSession' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/LiveQueryClient' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/LiveQuerySubscription' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/LocalDatastore' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/LocalDatastoreController' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/LocalDatastoreController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/LocalDatastoreUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ObjectStateMutations' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/OfflineQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Parse' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseACL' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseConfig' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/parseDate' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseError' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseFile' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseGeoPoint' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseHooks' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseInstallation' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseLiveQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseObject' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseOp' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParsePolygon' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseQuery' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseRelation' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseRole' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseSchema' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseSession' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/ParseUser' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/promiseUtils' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Push' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/RESTController' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/SingleInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Socket.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Storage' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/StorageController.browser' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/StorageController.default' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/StorageController.react-native' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/StorageController.weapp' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/TaskQueue' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/unique' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/UniqueInstanceStateController' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/unsavedChildren' {
    declare module.exports: any;
}

declare module 'parse/lib/weapp/Xhr.weapp' {
    declare module.exports: any;
}

declare module 'parse/node' {
    declare module.exports: any;
}

declare module 'parse/react-native' {
    declare module.exports: any;
}

declare module 'parse/weapp' {
    declare module.exports: any;
}

// Filename aliases
declare module 'parse/dist/parse.js' {
    declare module.exports: $Exports<'parse/dist/parse'>;
}
declare module 'parse/dist/parse.min.js' {
    declare module.exports: $Exports<'parse/dist/parse.min'>;
}
declare module 'parse/dist/parse.weapp.js' {
    declare module.exports: $Exports<'parse/dist/parse.weapp'>;
}
declare module 'parse/dist/parse.weapp.min.js' {
    declare module.exports: $Exports<'parse/dist/parse.weapp.min'>;
}
declare module 'parse/index' {
    declare module.exports: $Exports<'parse'>;
}
declare module 'parse/index.js' {
    declare module.exports: $Exports<'parse'>;
}
declare module 'parse/lib/browser/Analytics.js' {
    declare module.exports: $Exports<'parse/lib/browser/Analytics'>;
}
declare module 'parse/lib/browser/AnonymousUtils.js' {
    declare module.exports: $Exports<'parse/lib/browser/AnonymousUtils'>;
}
declare module 'parse/lib/browser/arrayContainsObject.js' {
    declare module.exports: $Exports<'parse/lib/browser/arrayContainsObject'>;
}
declare module 'parse/lib/browser/canBeSerialized.js' {
    declare module.exports: $Exports<'parse/lib/browser/canBeSerialized'>;
}
declare module 'parse/lib/browser/Cloud.js' {
    declare module.exports: $Exports<'parse/lib/browser/Cloud'>;
}
declare module 'parse/lib/browser/CloudCode.js' {
    declare module.exports: $Exports<'parse/lib/browser/CloudCode'>;
}
declare module 'parse/lib/browser/CoreManager.js' {
    declare module.exports: $Exports<'parse/lib/browser/CoreManager'>;
}
declare module 'parse/lib/browser/decode.js' {
    declare module.exports: $Exports<'parse/lib/browser/decode'>;
}
declare module 'parse/lib/browser/encode.js' {
    declare module.exports: $Exports<'parse/lib/browser/encode'>;
}
declare module 'parse/lib/browser/equals.js' {
    declare module.exports: $Exports<'parse/lib/browser/equals'>;
}
declare module 'parse/lib/browser/escape.js' {
    declare module.exports: $Exports<'parse/lib/browser/escape'>;
}
declare module 'parse/lib/browser/EventEmitter.js' {
    declare module.exports: $Exports<'parse/lib/browser/EventEmitter'>;
}
declare module 'parse/lib/browser/FacebookUtils.js' {
    declare module.exports: $Exports<'parse/lib/browser/FacebookUtils'>;
}
declare module 'parse/lib/browser/InstallationController.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/InstallationController',
    >;
}
declare module 'parse/lib/browser/isRevocableSession.js' {
    declare module.exports: $Exports<'parse/lib/browser/isRevocableSession'>;
}
declare module 'parse/lib/browser/LiveQueryClient.js' {
    declare module.exports: $Exports<'parse/lib/browser/LiveQueryClient'>;
}
declare module 'parse/lib/browser/LiveQuerySubscription.js' {
    declare module.exports: $Exports<'parse/lib/browser/LiveQuerySubscription'>;
}
declare module 'parse/lib/browser/LocalDatastore.js' {
    declare module.exports: $Exports<'parse/lib/browser/LocalDatastore'>;
}
declare module 'parse/lib/browser/LocalDatastoreController.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/LocalDatastoreController',
    >;
}
declare module 'parse/lib/browser/LocalDatastoreController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/LocalDatastoreController.react-native',
    >;
}
declare module 'parse/lib/browser/LocalDatastoreUtils.js' {
    declare module.exports: $Exports<'parse/lib/browser/LocalDatastoreUtils'>;
}
declare module 'parse/lib/browser/ObjectStateMutations.js' {
    declare module.exports: $Exports<'parse/lib/browser/ObjectStateMutations'>;
}
declare module 'parse/lib/browser/OfflineQuery.js' {
    declare module.exports: $Exports<'parse/lib/browser/OfflineQuery'>;
}
declare module 'parse/lib/browser/Parse.js' {
    declare module.exports: $Exports<'parse/lib/browser/Parse'>;
}
declare module 'parse/lib/browser/ParseACL.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseACL'>;
}
declare module 'parse/lib/browser/ParseConfig.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseConfig'>;
}
declare module 'parse/lib/browser/parseDate.js' {
    declare module.exports: $Exports<'parse/lib/browser/parseDate'>;
}
declare module 'parse/lib/browser/ParseError.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseError'>;
}
declare module 'parse/lib/browser/ParseFile.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseFile'>;
}
declare module 'parse/lib/browser/ParseGeoPoint.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseGeoPoint'>;
}
declare module 'parse/lib/browser/ParseHooks.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseHooks'>;
}
declare module 'parse/lib/browser/ParseInstallation.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseInstallation'>;
}
declare module 'parse/lib/browser/ParseLiveQuery.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseLiveQuery'>;
}
declare module 'parse/lib/browser/ParseObject.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseObject'>;
}
declare module 'parse/lib/browser/ParseOp.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseOp'>;
}
declare module 'parse/lib/browser/ParsePolygon.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParsePolygon'>;
}
declare module 'parse/lib/browser/ParseQuery.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseQuery'>;
}
declare module 'parse/lib/browser/ParseRelation.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseRelation'>;
}
declare module 'parse/lib/browser/ParseRole.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseRole'>;
}
declare module 'parse/lib/browser/ParseSchema.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseSchema'>;
}
declare module 'parse/lib/browser/ParseSession.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseSession'>;
}
declare module 'parse/lib/browser/ParseUser.js' {
    declare module.exports: $Exports<'parse/lib/browser/ParseUser'>;
}
declare module 'parse/lib/browser/promiseUtils.js' {
    declare module.exports: $Exports<'parse/lib/browser/promiseUtils'>;
}
declare module 'parse/lib/browser/Push.js' {
    declare module.exports: $Exports<'parse/lib/browser/Push'>;
}
declare module 'parse/lib/browser/RESTController.js' {
    declare module.exports: $Exports<'parse/lib/browser/RESTController'>;
}
declare module 'parse/lib/browser/SingleInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/SingleInstanceStateController',
    >;
}
declare module 'parse/lib/browser/Socket.weapp.js' {
    declare module.exports: $Exports<'parse/lib/browser/Socket.weapp'>;
}
declare module 'parse/lib/browser/Storage.js' {
    declare module.exports: $Exports<'parse/lib/browser/Storage'>;
}
declare module 'parse/lib/browser/StorageController.browser.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/StorageController.browser',
    >;
}
declare module 'parse/lib/browser/StorageController.default.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/StorageController.default',
    >;
}
declare module 'parse/lib/browser/StorageController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/StorageController.react-native',
    >;
}
declare module 'parse/lib/browser/StorageController.weapp.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/StorageController.weapp',
    >;
}
declare module 'parse/lib/browser/TaskQueue.js' {
    declare module.exports: $Exports<'parse/lib/browser/TaskQueue'>;
}
declare module 'parse/lib/browser/unique.js' {
    declare module.exports: $Exports<'parse/lib/browser/unique'>;
}
declare module 'parse/lib/browser/UniqueInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/browser/UniqueInstanceStateController',
    >;
}
declare module 'parse/lib/browser/unsavedChildren.js' {
    declare module.exports: $Exports<'parse/lib/browser/unsavedChildren'>;
}
declare module 'parse/lib/browser/Xhr.weapp.js' {
    declare module.exports: $Exports<'parse/lib/browser/Xhr.weapp'>;
}
declare module 'parse/lib/node/Analytics.js' {
    declare module.exports: $Exports<'parse/lib/node/Analytics'>;
}
declare module 'parse/lib/node/AnonymousUtils.js' {
    declare module.exports: $Exports<'parse/lib/node/AnonymousUtils'>;
}
declare module 'parse/lib/node/arrayContainsObject.js' {
    declare module.exports: $Exports<'parse/lib/node/arrayContainsObject'>;
}
declare module 'parse/lib/node/canBeSerialized.js' {
    declare module.exports: $Exports<'parse/lib/node/canBeSerialized'>;
}
declare module 'parse/lib/node/Cloud.js' {
    declare module.exports: $Exports<'parse/lib/node/Cloud'>;
}
declare module 'parse/lib/node/CloudCode.js' {
    declare module.exports: $Exports<'parse/lib/node/CloudCode'>;
}
declare module 'parse/lib/node/CoreManager.js' {
    declare module.exports: $Exports<'parse/lib/node/CoreManager'>;
}
declare module 'parse/lib/node/decode.js' {
    declare module.exports: $Exports<'parse/lib/node/decode'>;
}
declare module 'parse/lib/node/encode.js' {
    declare module.exports: $Exports<'parse/lib/node/encode'>;
}
declare module 'parse/lib/node/equals.js' {
    declare module.exports: $Exports<'parse/lib/node/equals'>;
}
declare module 'parse/lib/node/escape.js' {
    declare module.exports: $Exports<'parse/lib/node/escape'>;
}
declare module 'parse/lib/node/EventEmitter.js' {
    declare module.exports: $Exports<'parse/lib/node/EventEmitter'>;
}
declare module 'parse/lib/node/FacebookUtils.js' {
    declare module.exports: $Exports<'parse/lib/node/FacebookUtils'>;
}
declare module 'parse/lib/node/InstallationController.js' {
    declare module.exports: $Exports<'parse/lib/node/InstallationController'>;
}
declare module 'parse/lib/node/isRevocableSession.js' {
    declare module.exports: $Exports<'parse/lib/node/isRevocableSession'>;
}
declare module 'parse/lib/node/LiveQueryClient.js' {
    declare module.exports: $Exports<'parse/lib/node/LiveQueryClient'>;
}
declare module 'parse/lib/node/LiveQuerySubscription.js' {
    declare module.exports: $Exports<'parse/lib/node/LiveQuerySubscription'>;
}
declare module 'parse/lib/node/LocalDatastore.js' {
    declare module.exports: $Exports<'parse/lib/node/LocalDatastore'>;
}
declare module 'parse/lib/node/LocalDatastoreController.js' {
    declare module.exports: $Exports<'parse/lib/node/LocalDatastoreController'>;
}
declare module 'parse/lib/node/LocalDatastoreController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/node/LocalDatastoreController.react-native',
    >;
}
declare module 'parse/lib/node/LocalDatastoreUtils.js' {
    declare module.exports: $Exports<'parse/lib/node/LocalDatastoreUtils'>;
}
declare module 'parse/lib/node/ObjectStateMutations.js' {
    declare module.exports: $Exports<'parse/lib/node/ObjectStateMutations'>;
}
declare module 'parse/lib/node/OfflineQuery.js' {
    declare module.exports: $Exports<'parse/lib/node/OfflineQuery'>;
}
declare module 'parse/lib/node/Parse.js' {
    declare module.exports: $Exports<'parse/lib/node/Parse'>;
}
declare module 'parse/lib/node/ParseACL.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseACL'>;
}
declare module 'parse/lib/node/ParseConfig.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseConfig'>;
}
declare module 'parse/lib/node/parseDate.js' {
    declare module.exports: $Exports<'parse/lib/node/parseDate'>;
}
declare module 'parse/lib/node/ParseError.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseError'>;
}
declare module 'parse/lib/node/ParseFile.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseFile'>;
}
declare module 'parse/lib/node/ParseGeoPoint.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseGeoPoint'>;
}
declare module 'parse/lib/node/ParseHooks.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseHooks'>;
}
declare module 'parse/lib/node/ParseInstallation.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseInstallation'>;
}
declare module 'parse/lib/node/ParseLiveQuery.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseLiveQuery'>;
}
declare module 'parse/lib/node/ParseObject.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseObject'>;
}
declare module 'parse/lib/node/ParseOp.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseOp'>;
}
declare module 'parse/lib/node/ParsePolygon.js' {
    declare module.exports: $Exports<'parse/lib/node/ParsePolygon'>;
}
declare module 'parse/lib/node/ParseQuery.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseQuery'>;
}
declare module 'parse/lib/node/ParseRelation.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseRelation'>;
}
declare module 'parse/lib/node/ParseRole.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseRole'>;
}
declare module 'parse/lib/node/ParseSchema.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseSchema'>;
}
declare module 'parse/lib/node/ParseSession.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseSession'>;
}
declare module 'parse/lib/node/ParseUser.js' {
    declare module.exports: $Exports<'parse/lib/node/ParseUser'>;
}
declare module 'parse/lib/node/promiseUtils.js' {
    declare module.exports: $Exports<'parse/lib/node/promiseUtils'>;
}
declare module 'parse/lib/node/Push.js' {
    declare module.exports: $Exports<'parse/lib/node/Push'>;
}
declare module 'parse/lib/node/RESTController.js' {
    declare module.exports: $Exports<'parse/lib/node/RESTController'>;
}
declare module 'parse/lib/node/SingleInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/node/SingleInstanceStateController',
    >;
}
declare module 'parse/lib/node/Socket.weapp.js' {
    declare module.exports: $Exports<'parse/lib/node/Socket.weapp'>;
}
declare module 'parse/lib/node/Storage.js' {
    declare module.exports: $Exports<'parse/lib/node/Storage'>;
}
declare module 'parse/lib/node/StorageController.browser.js' {
    declare module.exports: $Exports<
        'parse/lib/node/StorageController.browser',
    >;
}
declare module 'parse/lib/node/StorageController.default.js' {
    declare module.exports: $Exports<
        'parse/lib/node/StorageController.default',
    >;
}
declare module 'parse/lib/node/StorageController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/node/StorageController.react-native',
    >;
}
declare module 'parse/lib/node/StorageController.weapp.js' {
    declare module.exports: $Exports<'parse/lib/node/StorageController.weapp'>;
}
declare module 'parse/lib/node/TaskQueue.js' {
    declare module.exports: $Exports<'parse/lib/node/TaskQueue'>;
}
declare module 'parse/lib/node/unique.js' {
    declare module.exports: $Exports<'parse/lib/node/unique'>;
}
declare module 'parse/lib/node/UniqueInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/node/UniqueInstanceStateController',
    >;
}
declare module 'parse/lib/node/unsavedChildren.js' {
    declare module.exports: $Exports<'parse/lib/node/unsavedChildren'>;
}
declare module 'parse/lib/node/Xhr.weapp.js' {
    declare module.exports: $Exports<'parse/lib/node/Xhr.weapp'>;
}
declare module 'parse/lib/react-native/Analytics.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Analytics'>;
}
declare module 'parse/lib/react-native/AnonymousUtils.js' {
    declare module.exports: $Exports<'parse/lib/react-native/AnonymousUtils'>;
}
declare module 'parse/lib/react-native/arrayContainsObject.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/arrayContainsObject',
    >;
}
declare module 'parse/lib/react-native/canBeSerialized.js' {
    declare module.exports: $Exports<'parse/lib/react-native/canBeSerialized'>;
}
declare module 'parse/lib/react-native/Cloud.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Cloud'>;
}
declare module 'parse/lib/react-native/CloudCode.js' {
    declare module.exports: $Exports<'parse/lib/react-native/CloudCode'>;
}
declare module 'parse/lib/react-native/CoreManager.js' {
    declare module.exports: $Exports<'parse/lib/react-native/CoreManager'>;
}
declare module 'parse/lib/react-native/decode.js' {
    declare module.exports: $Exports<'parse/lib/react-native/decode'>;
}
declare module 'parse/lib/react-native/encode.js' {
    declare module.exports: $Exports<'parse/lib/react-native/encode'>;
}
declare module 'parse/lib/react-native/equals.js' {
    declare module.exports: $Exports<'parse/lib/react-native/equals'>;
}
declare module 'parse/lib/react-native/escape.js' {
    declare module.exports: $Exports<'parse/lib/react-native/escape'>;
}
declare module 'parse/lib/react-native/EventEmitter.js' {
    declare module.exports: $Exports<'parse/lib/react-native/EventEmitter'>;
}
declare module 'parse/lib/react-native/FacebookUtils.js' {
    declare module.exports: $Exports<'parse/lib/react-native/FacebookUtils'>;
}
declare module 'parse/lib/react-native/InstallationController.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/InstallationController',
    >;
}
declare module 'parse/lib/react-native/isRevocableSession.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/isRevocableSession',
    >;
}
declare module 'parse/lib/react-native/LiveQueryClient.js' {
    declare module.exports: $Exports<'parse/lib/react-native/LiveQueryClient'>;
}
declare module 'parse/lib/react-native/LiveQuerySubscription.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/LiveQuerySubscription',
    >;
}
declare module 'parse/lib/react-native/LocalDatastore.js' {
    declare module.exports: $Exports<'parse/lib/react-native/LocalDatastore'>;
}
declare module 'parse/lib/react-native/LocalDatastoreController.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/LocalDatastoreController',
    >;
}
declare module 'parse/lib/react-native/LocalDatastoreController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/LocalDatastoreController.react-native',
    >;
}
declare module 'parse/lib/react-native/LocalDatastoreUtils.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/LocalDatastoreUtils',
    >;
}
declare module 'parse/lib/react-native/ObjectStateMutations.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/ObjectStateMutations',
    >;
}
declare module 'parse/lib/react-native/OfflineQuery.js' {
    declare module.exports: $Exports<'parse/lib/react-native/OfflineQuery'>;
}
declare module 'parse/lib/react-native/Parse.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Parse'>;
}
declare module 'parse/lib/react-native/ParseACL.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseACL'>;
}
declare module 'parse/lib/react-native/ParseConfig.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseConfig'>;
}
declare module 'parse/lib/react-native/parseDate.js' {
    declare module.exports: $Exports<'parse/lib/react-native/parseDate'>;
}
declare module 'parse/lib/react-native/ParseError.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseError'>;
}
declare module 'parse/lib/react-native/ParseFile.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseFile'>;
}
declare module 'parse/lib/react-native/ParseGeoPoint.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseGeoPoint'>;
}
declare module 'parse/lib/react-native/ParseHooks.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseHooks'>;
}
declare module 'parse/lib/react-native/ParseInstallation.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/ParseInstallation',
    >;
}
declare module 'parse/lib/react-native/ParseLiveQuery.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseLiveQuery'>;
}
declare module 'parse/lib/react-native/ParseObject.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseObject'>;
}
declare module 'parse/lib/react-native/ParseOp.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseOp'>;
}
declare module 'parse/lib/react-native/ParsePolygon.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParsePolygon'>;
}
declare module 'parse/lib/react-native/ParseQuery.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseQuery'>;
}
declare module 'parse/lib/react-native/ParseRelation.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseRelation'>;
}
declare module 'parse/lib/react-native/ParseRole.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseRole'>;
}
declare module 'parse/lib/react-native/ParseSchema.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseSchema'>;
}
declare module 'parse/lib/react-native/ParseSession.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseSession'>;
}
declare module 'parse/lib/react-native/ParseUser.js' {
    declare module.exports: $Exports<'parse/lib/react-native/ParseUser'>;
}
declare module 'parse/lib/react-native/promiseUtils.js' {
    declare module.exports: $Exports<'parse/lib/react-native/promiseUtils'>;
}
declare module 'parse/lib/react-native/Push.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Push'>;
}
declare module 'parse/lib/react-native/RESTController.js' {
    declare module.exports: $Exports<'parse/lib/react-native/RESTController'>;
}
declare module 'parse/lib/react-native/SingleInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/SingleInstanceStateController',
    >;
}
declare module 'parse/lib/react-native/Socket.weapp.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Socket.weapp'>;
}
declare module 'parse/lib/react-native/Storage.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Storage'>;
}
declare module 'parse/lib/react-native/StorageController.browser.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/StorageController.browser',
    >;
}
declare module 'parse/lib/react-native/StorageController.default.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/StorageController.default',
    >;
}
declare module 'parse/lib/react-native/StorageController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/StorageController.react-native',
    >;
}
declare module 'parse/lib/react-native/StorageController.weapp.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/StorageController.weapp',
    >;
}
declare module 'parse/lib/react-native/TaskQueue.js' {
    declare module.exports: $Exports<'parse/lib/react-native/TaskQueue'>;
}
declare module 'parse/lib/react-native/unique.js' {
    declare module.exports: $Exports<'parse/lib/react-native/unique'>;
}
declare module 'parse/lib/react-native/UniqueInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/react-native/UniqueInstanceStateController',
    >;
}
declare module 'parse/lib/react-native/unsavedChildren.js' {
    declare module.exports: $Exports<'parse/lib/react-native/unsavedChildren'>;
}
declare module 'parse/lib/react-native/Xhr.weapp.js' {
    declare module.exports: $Exports<'parse/lib/react-native/Xhr.weapp'>;
}
declare module 'parse/lib/weapp/Analytics.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Analytics'>;
}
declare module 'parse/lib/weapp/AnonymousUtils.js' {
    declare module.exports: $Exports<'parse/lib/weapp/AnonymousUtils'>;
}
declare module 'parse/lib/weapp/arrayContainsObject.js' {
    declare module.exports: $Exports<'parse/lib/weapp/arrayContainsObject'>;
}
declare module 'parse/lib/weapp/canBeSerialized.js' {
    declare module.exports: $Exports<'parse/lib/weapp/canBeSerialized'>;
}
declare module 'parse/lib/weapp/Cloud.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Cloud'>;
}
declare module 'parse/lib/weapp/CloudCode.js' {
    declare module.exports: $Exports<'parse/lib/weapp/CloudCode'>;
}
declare module 'parse/lib/weapp/CoreManager.js' {
    declare module.exports: $Exports<'parse/lib/weapp/CoreManager'>;
}
declare module 'parse/lib/weapp/decode.js' {
    declare module.exports: $Exports<'parse/lib/weapp/decode'>;
}
declare module 'parse/lib/weapp/encode.js' {
    declare module.exports: $Exports<'parse/lib/weapp/encode'>;
}
declare module 'parse/lib/weapp/equals.js' {
    declare module.exports: $Exports<'parse/lib/weapp/equals'>;
}
declare module 'parse/lib/weapp/escape.js' {
    declare module.exports: $Exports<'parse/lib/weapp/escape'>;
}
declare module 'parse/lib/weapp/EventEmitter.js' {
    declare module.exports: $Exports<'parse/lib/weapp/EventEmitter'>;
}
declare module 'parse/lib/weapp/FacebookUtils.js' {
    declare module.exports: $Exports<'parse/lib/weapp/FacebookUtils'>;
}
declare module 'parse/lib/weapp/InstallationController.js' {
    declare module.exports: $Exports<'parse/lib/weapp/InstallationController'>;
}
declare module 'parse/lib/weapp/isRevocableSession.js' {
    declare module.exports: $Exports<'parse/lib/weapp/isRevocableSession'>;
}
declare module 'parse/lib/weapp/LiveQueryClient.js' {
    declare module.exports: $Exports<'parse/lib/weapp/LiveQueryClient'>;
}
declare module 'parse/lib/weapp/LiveQuerySubscription.js' {
    declare module.exports: $Exports<'parse/lib/weapp/LiveQuerySubscription'>;
}
declare module 'parse/lib/weapp/LocalDatastore.js' {
    declare module.exports: $Exports<'parse/lib/weapp/LocalDatastore'>;
}
declare module 'parse/lib/weapp/LocalDatastoreController.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/LocalDatastoreController',
    >;
}
declare module 'parse/lib/weapp/LocalDatastoreController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/LocalDatastoreController.react-native',
    >;
}
declare module 'parse/lib/weapp/LocalDatastoreUtils.js' {
    declare module.exports: $Exports<'parse/lib/weapp/LocalDatastoreUtils'>;
}
declare module 'parse/lib/weapp/ObjectStateMutations.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ObjectStateMutations'>;
}
declare module 'parse/lib/weapp/OfflineQuery.js' {
    declare module.exports: $Exports<'parse/lib/weapp/OfflineQuery'>;
}
declare module 'parse/lib/weapp/Parse.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Parse'>;
}
declare module 'parse/lib/weapp/ParseACL.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseACL'>;
}
declare module 'parse/lib/weapp/ParseConfig.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseConfig'>;
}
declare module 'parse/lib/weapp/parseDate.js' {
    declare module.exports: $Exports<'parse/lib/weapp/parseDate'>;
}
declare module 'parse/lib/weapp/ParseError.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseError'>;
}
declare module 'parse/lib/weapp/ParseFile.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseFile'>;
}
declare module 'parse/lib/weapp/ParseGeoPoint.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseGeoPoint'>;
}
declare module 'parse/lib/weapp/ParseHooks.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseHooks'>;
}
declare module 'parse/lib/weapp/ParseInstallation.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseInstallation'>;
}
declare module 'parse/lib/weapp/ParseLiveQuery.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseLiveQuery'>;
}
declare module 'parse/lib/weapp/ParseObject.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseObject'>;
}
declare module 'parse/lib/weapp/ParseOp.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseOp'>;
}
declare module 'parse/lib/weapp/ParsePolygon.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParsePolygon'>;
}
declare module 'parse/lib/weapp/ParseQuery.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseQuery'>;
}
declare module 'parse/lib/weapp/ParseRelation.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseRelation'>;
}
declare module 'parse/lib/weapp/ParseRole.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseRole'>;
}
declare module 'parse/lib/weapp/ParseSchema.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseSchema'>;
}
declare module 'parse/lib/weapp/ParseSession.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseSession'>;
}
declare module 'parse/lib/weapp/ParseUser.js' {
    declare module.exports: $Exports<'parse/lib/weapp/ParseUser'>;
}
declare module 'parse/lib/weapp/promiseUtils.js' {
    declare module.exports: $Exports<'parse/lib/weapp/promiseUtils'>;
}
declare module 'parse/lib/weapp/Push.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Push'>;
}
declare module 'parse/lib/weapp/RESTController.js' {
    declare module.exports: $Exports<'parse/lib/weapp/RESTController'>;
}
declare module 'parse/lib/weapp/SingleInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/SingleInstanceStateController',
    >;
}
declare module 'parse/lib/weapp/Socket.weapp.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Socket.weapp'>;
}
declare module 'parse/lib/weapp/Storage.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Storage'>;
}
declare module 'parse/lib/weapp/StorageController.browser.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/StorageController.browser',
    >;
}
declare module 'parse/lib/weapp/StorageController.default.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/StorageController.default',
    >;
}
declare module 'parse/lib/weapp/StorageController.react-native.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/StorageController.react-native',
    >;
}
declare module 'parse/lib/weapp/StorageController.weapp.js' {
    declare module.exports: $Exports<'parse/lib/weapp/StorageController.weapp'>;
}
declare module 'parse/lib/weapp/TaskQueue.js' {
    declare module.exports: $Exports<'parse/lib/weapp/TaskQueue'>;
}
declare module 'parse/lib/weapp/unique.js' {
    declare module.exports: $Exports<'parse/lib/weapp/unique'>;
}
declare module 'parse/lib/weapp/UniqueInstanceStateController.js' {
    declare module.exports: $Exports<
        'parse/lib/weapp/UniqueInstanceStateController',
    >;
}
declare module 'parse/lib/weapp/unsavedChildren.js' {
    declare module.exports: $Exports<'parse/lib/weapp/unsavedChildren'>;
}
declare module 'parse/lib/weapp/Xhr.weapp.js' {
    declare module.exports: $Exports<'parse/lib/weapp/Xhr.weapp'>;
}
declare module 'parse/node.js' {
    declare module.exports: $Exports<'parse/node'>;
}
declare module 'parse/react-native.js' {
    declare module.exports: $Exports<'parse/react-native'>;
}
declare module 'parse/weapp.js' {
    declare module.exports: $Exports<'parse/weapp'>;
}
