// flow-typed signature: 149cebbba75c5183d598710849cc5dfa
// flow-typed version: <<STUB>>/querystring-browser_v^1.0.4/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'querystring-browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'querystring-browser' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'querystring-browser/querystring' {
    declare module.exports: any;
}

declare module 'querystring-browser/test/core-tests/test-querystring-maxKeys-non-finite' {
    declare module.exports: any;
}

declare module 'querystring-browser/test/core-tests/test-querystring-multichar-separator' {
    declare module.exports: any;
}

declare module 'querystring-browser/test/core-tests/test-querystring' {
    declare module.exports: any;
}

declare module 'querystring-browser/test/test' {
    declare module.exports: any;
}

// Filename aliases
declare module 'querystring-browser/querystring.js' {
    declare module.exports: $Exports<'querystring-browser/querystring'>;
}
declare module 'querystring-browser/test/core-tests/test-querystring-maxKeys-non-finite.js' {
    declare module.exports: $Exports<
        'querystring-browser/test/core-tests/test-querystring-maxKeys-non-finite',
    >;
}
declare module 'querystring-browser/test/core-tests/test-querystring-multichar-separator.js' {
    declare module.exports: $Exports<
        'querystring-browser/test/core-tests/test-querystring-multichar-separator',
    >;
}
declare module 'querystring-browser/test/core-tests/test-querystring.js' {
    declare module.exports: $Exports<
        'querystring-browser/test/core-tests/test-querystring',
    >;
}
declare module 'querystring-browser/test/test.js' {
    declare module.exports: $Exports<'querystring-browser/test/test'>;
}
