// flow-typed signature: 1606f3beb6473fcb51866e650d09795f
// flow-typed version: <<STUB>>/react-router-config_v^5.1.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-config' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-config/cjs/react-router-config' {
    declare module.exports: any;
}

declare module 'react-router-config/cjs/react-router-config.min' {
    declare module.exports: any;
}

declare module 'react-router-config/es/matchRoutes' {
    declare module.exports: any;
}

declare module 'react-router-config/es/renderRoutes' {
    declare module.exports: any;
}

declare module 'react-router-config/es/warnAboutDeprecatedESMImport' {
    declare module.exports: any;
}

declare module 'react-router-config/esm/react-router-config' {
    declare module.exports: any;
}

declare module 'react-router-config/matchRoutes' {
    declare module.exports: any;
}

declare module 'react-router-config/modules' {
    declare module.exports: any;
}

declare module 'react-router-config/modules/matchRoutes' {
    declare module.exports: any;
}

declare module 'react-router-config/modules/renderRoutes' {
    declare module.exports: any;
}

declare module 'react-router-config/renderRoutes' {
    declare module.exports: any;
}

declare module 'react-router-config/umd/react-router-config' {
    declare module.exports: any;
}

declare module 'react-router-config/umd/react-router-config.min' {
    declare module.exports: any;
}

declare module 'react-router-config/warnAboutDeprecatedCJSRequire' {
    declare module.exports: any;
}

// Filename aliases
declare module 'react-router-config/cjs/react-router-config.js' {
    declare module.exports: $Exports<
        'react-router-config/cjs/react-router-config',
    >;
}
declare module 'react-router-config/cjs/react-router-config.min.js' {
    declare module.exports: $Exports<
        'react-router-config/cjs/react-router-config.min',
    >;
}
declare module 'react-router-config/es/matchRoutes.js' {
    declare module.exports: $Exports<'react-router-config/es/matchRoutes'>;
}
declare module 'react-router-config/es/renderRoutes.js' {
    declare module.exports: $Exports<'react-router-config/es/renderRoutes'>;
}
declare module 'react-router-config/es/warnAboutDeprecatedESMImport.js' {
    declare module.exports: $Exports<
        'react-router-config/es/warnAboutDeprecatedESMImport',
    >;
}
declare module 'react-router-config/esm/react-router-config.js' {
    declare module.exports: $Exports<
        'react-router-config/esm/react-router-config',
    >;
}
declare module 'react-router-config/index' {
    declare module.exports: $Exports<'react-router-config'>;
}
declare module 'react-router-config/index.js' {
    declare module.exports: $Exports<'react-router-config'>;
}
declare module 'react-router-config/matchRoutes.js' {
    declare module.exports: $Exports<'react-router-config/matchRoutes'>;
}
declare module 'react-router-config/modules/index' {
    declare module.exports: $Exports<'react-router-config/modules'>;
}
declare module 'react-router-config/modules/index.js' {
    declare module.exports: $Exports<'react-router-config/modules'>;
}
declare module 'react-router-config/modules/matchRoutes.js' {
    declare module.exports: $Exports<'react-router-config/modules/matchRoutes'>;
}
declare module 'react-router-config/modules/renderRoutes.js' {
    declare module.exports: $Exports<
        'react-router-config/modules/renderRoutes',
    >;
}
declare module 'react-router-config/renderRoutes.js' {
    declare module.exports: $Exports<'react-router-config/renderRoutes'>;
}
declare module 'react-router-config/umd/react-router-config.js' {
    declare module.exports: $Exports<
        'react-router-config/umd/react-router-config',
    >;
}
declare module 'react-router-config/umd/react-router-config.min.js' {
    declare module.exports: $Exports<
        'react-router-config/umd/react-router-config.min',
    >;
}
declare module 'react-router-config/warnAboutDeprecatedCJSRequire.js' {
    declare module.exports: $Exports<
        'react-router-config/warnAboutDeprecatedCJSRequire',
    >;
}
