// flow-typed signature: cc60595f831502c2da1fc19d04ab8a00
// flow-typed version: <<STUB>>/readdir-recursive_v0.0.4/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'readdir-recursive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'readdir-recursive' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'readdir-recursive/index' {
    declare module.exports: $Exports<'readdir-recursive'>;
}
declare module 'readdir-recursive/index.js' {
    declare module.exports: $Exports<'readdir-recursive'>;
}
