// flow-typed signature: 511dd72f127bf8d782adeee6638f6bdb
// flow-typed version: <<STUB>>/redux-super-thunk_v0.0.8/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-super-thunk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-super-thunk' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-super-thunk/dist/redux-super-thunk' {
    declare module.exports: any;
}

declare module 'redux-super-thunk/dist/redux-super-thunk.min' {
    declare module.exports: any;
}

declare module 'redux-super-thunk/es' {
    declare module.exports: any;
}

declare module 'redux-super-thunk/lib' {
    declare module.exports: any;
}

declare module 'redux-super-thunk/src' {
    declare module.exports: any;
}

// Filename aliases
declare module 'redux-super-thunk/dist/redux-super-thunk.js' {
    declare module.exports: $Exports<
        'redux-super-thunk/dist/redux-super-thunk',
    >;
}
declare module 'redux-super-thunk/dist/redux-super-thunk.min.js' {
    declare module.exports: $Exports<
        'redux-super-thunk/dist/redux-super-thunk.min',
    >;
}
declare module 'redux-super-thunk/es/index' {
    declare module.exports: $Exports<'redux-super-thunk/es'>;
}
declare module 'redux-super-thunk/es/index.js' {
    declare module.exports: $Exports<'redux-super-thunk/es'>;
}
declare module 'redux-super-thunk/lib/index' {
    declare module.exports: $Exports<'redux-super-thunk/lib'>;
}
declare module 'redux-super-thunk/lib/index.js' {
    declare module.exports: $Exports<'redux-super-thunk/lib'>;
}
declare module 'redux-super-thunk/src/index' {
    declare module.exports: $Exports<'redux-super-thunk/src'>;
}
declare module 'redux-super-thunk/src/index.js' {
    declare module.exports: $Exports<'redux-super-thunk/src'>;
}
