// flow-typed signature: 0cb6d446c6fb3bebcb3f884102b04690
// flow-typed version: <<STUB>>/redux-local-persist_v0.1.0/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-local-persist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-local-persist' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-local-persist/lib' {
    declare module.exports: any;
}

declare module 'redux-local-persist/src' {
    declare module.exports: any;
}

// Filename aliases
declare module 'redux-local-persist/lib/index' {
    declare module.exports: $Exports<'redux-local-persist/lib'>;
}
declare module 'redux-local-persist/lib/index.js' {
    declare module.exports: $Exports<'redux-local-persist/lib'>;
}
declare module 'redux-local-persist/src/index' {
    declare module.exports: $Exports<'redux-local-persist/src'>;
}
declare module 'redux-local-persist/src/index.js' {
    declare module.exports: $Exports<'redux-local-persist/src'>;
}
