// flow-typed signature: 31b382a0d83c0f23df315358e361ff3b
// flow-typed version: <<STUB>>/run-script-os_v^1.0.7/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'run-script-os'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'run-script-os' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'run-script-os/index' {
    declare module.exports: $Exports<'run-script-os'>;
}
declare module 'run-script-os/index.js' {
    declare module.exports: $Exports<'run-script-os'>;
}
