// flow-typed signature: fe2907a393f12a9f9c74073f1e6974af
// flow-typed version: <<STUB>>/underscore_v*/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'underscore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'underscore' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'underscore/underscore-min' {
    declare module.exports: any;
}

declare module 'underscore/underscore' {
    declare module.exports: any;
}

// Filename aliases
declare module 'underscore/underscore-min.js' {
    declare module.exports: $Exports<'underscore/underscore-min'>;
}
declare module 'underscore/underscore.js' {
    declare module.exports: $Exports<'underscore/underscore'>;
}
