// flow-typed signature: 94c5b9e312aa8ddb858766df614ee14e
// flow-typed version: <<STUB>>/workbox-build_v^4.3.1/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'workbox-build'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'workbox-build' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'workbox-build/build/_types' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/generate-sw-string' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/generate-sw' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/get-manifest' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/inject-manifest' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/base-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/common-generate-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/defaults' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/generate-sw-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/generate-sw-string-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/get-manifest-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/inject-manifest-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/reg-exp-object' {
    declare module.exports: any;
}

declare module 'workbox-build/build/entry-points/options/validate' {
    declare module.exports: any;
}

declare module 'workbox-build/build' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/cdn-utils' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/check-for-deprecated-options' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/copy-workbox-libraries' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/errors' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/filter-files' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-composite-details' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-file-details' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-file-hash' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-file-manifest-entries' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-file-size' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-string-details' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/get-string-hash' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/maximum-size-transform' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/modify-url-prefix-transform' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/no-revision-for-urls-matching-transform' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/populate-sw-template' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/runtime-caching-converter' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/stringify-without-comments' {
    declare module.exports: any;
}

declare module 'workbox-build/build/lib/write-sw-using-default-template' {
    declare module.exports: any;
}

declare module 'workbox-build/build/templates/sw-template' {
    declare module.exports: any;
}

declare module 'workbox-build/src/_types' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/generate-sw-string' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/generate-sw' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/get-manifest' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/inject-manifest' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/base-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/common-generate-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/defaults' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/generate-sw-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/generate-sw-string-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/get-manifest-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/inject-manifest-schema' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/reg-exp-object' {
    declare module.exports: any;
}

declare module 'workbox-build/src/entry-points/options/validate' {
    declare module.exports: any;
}

declare module 'workbox-build/src' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/cdn-utils' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/check-for-deprecated-options' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/copy-workbox-libraries' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/errors' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/filter-files' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-composite-details' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-file-details' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-file-hash' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-file-manifest-entries' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-file-size' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-string-details' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/get-string-hash' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/maximum-size-transform' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/modify-url-prefix-transform' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/no-revision-for-urls-matching-transform' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/populate-sw-template' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/runtime-caching-converter' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/stringify-without-comments' {
    declare module.exports: any;
}

declare module 'workbox-build/src/lib/write-sw-using-default-template' {
    declare module.exports: any;
}

declare module 'workbox-build/src/templates/sw-template' {
    declare module.exports: any;
}

// Filename aliases
declare module 'workbox-build/build/_types.js' {
    declare module.exports: $Exports<'workbox-build/build/_types'>;
}
declare module 'workbox-build/build/entry-points/generate-sw-string.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/generate-sw-string',
    >;
}
declare module 'workbox-build/build/entry-points/generate-sw.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/generate-sw',
    >;
}
declare module 'workbox-build/build/entry-points/get-manifest.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/get-manifest',
    >;
}
declare module 'workbox-build/build/entry-points/inject-manifest.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/inject-manifest',
    >;
}
declare module 'workbox-build/build/entry-points/options/base-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/base-schema',
    >;
}
declare module 'workbox-build/build/entry-points/options/common-generate-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/common-generate-schema',
    >;
}
declare module 'workbox-build/build/entry-points/options/defaults.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/defaults',
    >;
}
declare module 'workbox-build/build/entry-points/options/generate-sw-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/generate-sw-schema',
    >;
}
declare module 'workbox-build/build/entry-points/options/generate-sw-string-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/generate-sw-string-schema',
    >;
}
declare module 'workbox-build/build/entry-points/options/get-manifest-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/get-manifest-schema',
    >;
}
declare module 'workbox-build/build/entry-points/options/inject-manifest-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/inject-manifest-schema',
    >;
}
declare module 'workbox-build/build/entry-points/options/reg-exp-object.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/reg-exp-object',
    >;
}
declare module 'workbox-build/build/entry-points/options/validate.js' {
    declare module.exports: $Exports<
        'workbox-build/build/entry-points/options/validate',
    >;
}
declare module 'workbox-build/build/index' {
    declare module.exports: $Exports<'workbox-build/build'>;
}
declare module 'workbox-build/build/index.js' {
    declare module.exports: $Exports<'workbox-build/build'>;
}
declare module 'workbox-build/build/lib/cdn-utils.js' {
    declare module.exports: $Exports<'workbox-build/build/lib/cdn-utils'>;
}
declare module 'workbox-build/build/lib/check-for-deprecated-options.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/check-for-deprecated-options',
    >;
}
declare module 'workbox-build/build/lib/copy-workbox-libraries.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/copy-workbox-libraries',
    >;
}
declare module 'workbox-build/build/lib/errors.js' {
    declare module.exports: $Exports<'workbox-build/build/lib/errors'>;
}
declare module 'workbox-build/build/lib/filter-files.js' {
    declare module.exports: $Exports<'workbox-build/build/lib/filter-files'>;
}
declare module 'workbox-build/build/lib/get-composite-details.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/get-composite-details',
    >;
}
declare module 'workbox-build/build/lib/get-file-details.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/get-file-details',
    >;
}
declare module 'workbox-build/build/lib/get-file-hash.js' {
    declare module.exports: $Exports<'workbox-build/build/lib/get-file-hash'>;
}
declare module 'workbox-build/build/lib/get-file-manifest-entries.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/get-file-manifest-entries',
    >;
}
declare module 'workbox-build/build/lib/get-file-size.js' {
    declare module.exports: $Exports<'workbox-build/build/lib/get-file-size'>;
}
declare module 'workbox-build/build/lib/get-string-details.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/get-string-details',
    >;
}
declare module 'workbox-build/build/lib/get-string-hash.js' {
    declare module.exports: $Exports<'workbox-build/build/lib/get-string-hash'>;
}
declare module 'workbox-build/build/lib/maximum-size-transform.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/maximum-size-transform',
    >;
}
declare module 'workbox-build/build/lib/modify-url-prefix-transform.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/modify-url-prefix-transform',
    >;
}
declare module 'workbox-build/build/lib/no-revision-for-urls-matching-transform.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/no-revision-for-urls-matching-transform',
    >;
}
declare module 'workbox-build/build/lib/populate-sw-template.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/populate-sw-template',
    >;
}
declare module 'workbox-build/build/lib/runtime-caching-converter.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/runtime-caching-converter',
    >;
}
declare module 'workbox-build/build/lib/stringify-without-comments.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/stringify-without-comments',
    >;
}
declare module 'workbox-build/build/lib/write-sw-using-default-template.js' {
    declare module.exports: $Exports<
        'workbox-build/build/lib/write-sw-using-default-template',
    >;
}
declare module 'workbox-build/build/templates/sw-template.js' {
    declare module.exports: $Exports<
        'workbox-build/build/templates/sw-template',
    >;
}
declare module 'workbox-build/src/_types.js' {
    declare module.exports: $Exports<'workbox-build/src/_types'>;
}
declare module 'workbox-build/src/entry-points/generate-sw-string.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/generate-sw-string',
    >;
}
declare module 'workbox-build/src/entry-points/generate-sw.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/generate-sw',
    >;
}
declare module 'workbox-build/src/entry-points/get-manifest.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/get-manifest',
    >;
}
declare module 'workbox-build/src/entry-points/inject-manifest.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/inject-manifest',
    >;
}
declare module 'workbox-build/src/entry-points/options/base-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/base-schema',
    >;
}
declare module 'workbox-build/src/entry-points/options/common-generate-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/common-generate-schema',
    >;
}
declare module 'workbox-build/src/entry-points/options/defaults.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/defaults',
    >;
}
declare module 'workbox-build/src/entry-points/options/generate-sw-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/generate-sw-schema',
    >;
}
declare module 'workbox-build/src/entry-points/options/generate-sw-string-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/generate-sw-string-schema',
    >;
}
declare module 'workbox-build/src/entry-points/options/get-manifest-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/get-manifest-schema',
    >;
}
declare module 'workbox-build/src/entry-points/options/inject-manifest-schema.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/inject-manifest-schema',
    >;
}
declare module 'workbox-build/src/entry-points/options/reg-exp-object.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/reg-exp-object',
    >;
}
declare module 'workbox-build/src/entry-points/options/validate.js' {
    declare module.exports: $Exports<
        'workbox-build/src/entry-points/options/validate',
    >;
}
declare module 'workbox-build/src/index' {
    declare module.exports: $Exports<'workbox-build/src'>;
}
declare module 'workbox-build/src/index.js' {
    declare module.exports: $Exports<'workbox-build/src'>;
}
declare module 'workbox-build/src/lib/cdn-utils.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/cdn-utils'>;
}
declare module 'workbox-build/src/lib/check-for-deprecated-options.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/check-for-deprecated-options',
    >;
}
declare module 'workbox-build/src/lib/copy-workbox-libraries.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/copy-workbox-libraries',
    >;
}
declare module 'workbox-build/src/lib/errors.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/errors'>;
}
declare module 'workbox-build/src/lib/filter-files.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/filter-files'>;
}
declare module 'workbox-build/src/lib/get-composite-details.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/get-composite-details',
    >;
}
declare module 'workbox-build/src/lib/get-file-details.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/get-file-details'>;
}
declare module 'workbox-build/src/lib/get-file-hash.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/get-file-hash'>;
}
declare module 'workbox-build/src/lib/get-file-manifest-entries.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/get-file-manifest-entries',
    >;
}
declare module 'workbox-build/src/lib/get-file-size.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/get-file-size'>;
}
declare module 'workbox-build/src/lib/get-string-details.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/get-string-details',
    >;
}
declare module 'workbox-build/src/lib/get-string-hash.js' {
    declare module.exports: $Exports<'workbox-build/src/lib/get-string-hash'>;
}
declare module 'workbox-build/src/lib/maximum-size-transform.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/maximum-size-transform',
    >;
}
declare module 'workbox-build/src/lib/modify-url-prefix-transform.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/modify-url-prefix-transform',
    >;
}
declare module 'workbox-build/src/lib/no-revision-for-urls-matching-transform.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/no-revision-for-urls-matching-transform',
    >;
}
declare module 'workbox-build/src/lib/populate-sw-template.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/populate-sw-template',
    >;
}
declare module 'workbox-build/src/lib/runtime-caching-converter.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/runtime-caching-converter',
    >;
}
declare module 'workbox-build/src/lib/stringify-without-comments.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/stringify-without-comments',
    >;
}
declare module 'workbox-build/src/lib/write-sw-using-default-template.js' {
    declare module.exports: $Exports<
        'workbox-build/src/lib/write-sw-using-default-template',
    >;
}
declare module 'workbox-build/src/templates/sw-template.js' {
    declare module.exports: $Exports<'workbox-build/src/templates/sw-template'>;
}
