// flow-typed signature: 414d785df1d79134881083b31e0990fc
// flow-typed version: <<STUB>>/xss_v^1.0.6/flow_v0.116.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xss' {
    declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xss/dist/xss' {
    declare module.exports: any;
}

declare module 'xss/dist/xss.min' {
    declare module.exports: any;
}

declare module 'xss/lib/cli' {
    declare module.exports: any;
}

declare module 'xss/lib/default' {
    declare module.exports: any;
}

declare module 'xss/lib' {
    declare module.exports: any;
}

declare module 'xss/lib/parser' {
    declare module.exports: any;
}

declare module 'xss/lib/util' {
    declare module.exports: any;
}

declare module 'xss/lib/xss' {
    declare module.exports: any;
}

// Filename aliases
declare module 'xss/dist/xss.js' {
    declare module.exports: $Exports<'xss/dist/xss'>;
}
declare module 'xss/dist/xss.min.js' {
    declare module.exports: $Exports<'xss/dist/xss.min'>;
}
declare module 'xss/lib/cli.js' {
    declare module.exports: $Exports<'xss/lib/cli'>;
}
declare module 'xss/lib/default.js' {
    declare module.exports: $Exports<'xss/lib/default'>;
}
declare module 'xss/lib/index' {
    declare module.exports: $Exports<'xss/lib'>;
}
declare module 'xss/lib/index.js' {
    declare module.exports: $Exports<'xss/lib'>;
}
declare module 'xss/lib/parser.js' {
    declare module.exports: $Exports<'xss/lib/parser'>;
}
declare module 'xss/lib/util.js' {
    declare module.exports: $Exports<'xss/lib/util'>;
}
declare module 'xss/lib/xss.js' {
    declare module.exports: $Exports<'xss/lib/xss'>;
}
