export default {
    ADD_PLUGIN: 'ADD_PLUGIN',
    UPDATE_PLUGIN: 'UPDATE_PLUGIN',
    REMOVE_PLUGIN: 'REMOVE_PLUGIN',
    ADD_PLUGIN_CONTROLS: 'ADD_PLUGIN_CONTROLS',
    REMOVE_PLUGIN_CONTROLS: 'REMOVE_PLUGIN_CONTROLS',
};
