// THIS FILE IS GENERATED BY THE `$ arcli icons` command
// DO NOT DIRECTLY EDIT !!!!!!!!!!!!!!!!

import Activity from './svgs/Activity';
import Airplay from './svgs/Airplay';
import AlertCircle from './svgs/AlertCircle';
import AlertOctagon from './svgs/AlertOctagon';
import AlertTriangle from './svgs/AlertTriangle';
import AlignCenter from './svgs/AlignCenter';
import AlignJustify from './svgs/AlignJustify';
import AlignLeft from './svgs/AlignLeft';
import AlignRight from './svgs/AlignRight';
import Anchor from './svgs/Anchor';
import Aperture from './svgs/Aperture';
import Archive from './svgs/Archive';
import ArrowDown from './svgs/ArrowDown';
import ArrowDownCircle from './svgs/ArrowDownCircle';
import ArrowDownLeft from './svgs/ArrowDownLeft';
import ArrowDownRight from './svgs/ArrowDownRight';
import ArrowLeft from './svgs/ArrowLeft';
import ArrowLeftCircle from './svgs/ArrowLeftCircle';
import ArrowRight from './svgs/ArrowRight';
import ArrowRightCircle from './svgs/ArrowRightCircle';
import ArrowUp from './svgs/ArrowUp';
import ArrowUpCircle from './svgs/ArrowUpCircle';
import ArrowUpLeft from './svgs/ArrowUpLeft';
import ArrowUpRight from './svgs/ArrowUpRight';
import AtSign from './svgs/AtSign';
import Award from './svgs/Award';
import BarChart from './svgs/BarChart';
import BarChart2 from './svgs/BarChart2';
import Battery from './svgs/Battery';
import BatteryCharging from './svgs/BatteryCharging';
import Bell from './svgs/Bell';
import BellOff from './svgs/BellOff';
import Bluetooth from './svgs/Bluetooth';
import Bold from './svgs/Bold';
import Book from './svgs/Book';
import BookOpen from './svgs/BookOpen';
import Bookmark from './svgs/Bookmark';
import Box from './svgs/Box';
import Briefcase from './svgs/Briefcase';
import Calendar from './svgs/Calendar';
import Camera from './svgs/Camera';
import CameraOff from './svgs/CameraOff';
import Cast from './svgs/Cast';
import Check from './svgs/Check';
import CheckCircle from './svgs/CheckCircle';
import CheckSquare from './svgs/CheckSquare';
import ChevronDown from './svgs/ChevronDown';
import ChevronLeft from './svgs/ChevronLeft';
import ChevronRight from './svgs/ChevronRight';
import ChevronUp from './svgs/ChevronUp';
import ChevronsDown from './svgs/ChevronsDown';
import ChevronsLeft from './svgs/ChevronsLeft';
import ChevronsRight from './svgs/ChevronsRight';
import ChevronsUp from './svgs/ChevronsUp';
import Chrome from './svgs/Chrome';
import Circle from './svgs/Circle';
import Clipboard from './svgs/Clipboard';
import Clock from './svgs/Clock';
import Cloud from './svgs/Cloud';
import CloudDrizzle from './svgs/CloudDrizzle';
import CloudLightning from './svgs/CloudLightning';
import CloudOff from './svgs/CloudOff';
import CloudRain from './svgs/CloudRain';
import CloudSnow from './svgs/CloudSnow';
import Code from './svgs/Code';
import Codepen from './svgs/Codepen';
import Command from './svgs/Command';
import Compass from './svgs/Compass';
import Copy from './svgs/Copy';
import CornerDownLeft from './svgs/CornerDownLeft';
import CornerDownRight from './svgs/CornerDownRight';
import CornerLeftDown from './svgs/CornerLeftDown';
import CornerLeftUp from './svgs/CornerLeftUp';
import CornerRightDown from './svgs/CornerRightDown';
import CornerRightUp from './svgs/CornerRightUp';
import CornerUpLeft from './svgs/CornerUpLeft';
import CornerUpRight from './svgs/CornerUpRight';
import Cpu from './svgs/Cpu';
import CreditCard from './svgs/CreditCard';
import Crop from './svgs/Crop';
import Crosshair from './svgs/Crosshair';
import Database from './svgs/Database';
import Delete from './svgs/Delete';
import Disc from './svgs/Disc';
import DollarSign from './svgs/DollarSign';
import Download from './svgs/Download';
import DownloadCloud from './svgs/DownloadCloud';
import Droplet from './svgs/Droplet';
import Edit from './svgs/Edit';
import Edit2 from './svgs/Edit2';
import Edit3 from './svgs/Edit3';
import ExternalLink from './svgs/ExternalLink';
import Eye from './svgs/Eye';
import EyeOff from './svgs/EyeOff';
import Facebook from './svgs/Facebook';
import FastForward from './svgs/FastForward';
import Feather from './svgs/Feather';
import File from './svgs/File';
import FileMinus from './svgs/FileMinus';
import FilePlus from './svgs/FilePlus';
import FileText from './svgs/FileText';
import Film from './svgs/Film';
import Filter from './svgs/Filter';
import Flag from './svgs/Flag';
import Folder from './svgs/Folder';
import FolderMinus from './svgs/FolderMinus';
import FolderPlus from './svgs/FolderPlus';
import Gift from './svgs/Gift';
import GitBranch from './svgs/GitBranch';
import GitCommit from './svgs/GitCommit';
import GitMerge from './svgs/GitMerge';
import GitPullRequest from './svgs/GitPullRequest';
import Github from './svgs/Github';
import Gitlab from './svgs/Gitlab';
import Globe from './svgs/Globe';
import Grid from './svgs/Grid';
import HardDrive from './svgs/HardDrive';
import Hash from './svgs/Hash';
import Headphones from './svgs/Headphones';
import Heart from './svgs/Heart';
import HelpCircle from './svgs/HelpCircle';
import Home from './svgs/Home';
import Image from './svgs/Image';
import Inbox from './svgs/Inbox';
import Info from './svgs/Info';
import Instagram from './svgs/Instagram';
import Italic from './svgs/Italic';
import Layers from './svgs/Layers';
import Layout from './svgs/Layout';
import LifeBuoy from './svgs/LifeBuoy';
import Link from './svgs/Link';
import Link2 from './svgs/Link2';
import Linkedin from './svgs/Linkedin';
import List from './svgs/List';
import Loader from './svgs/Loader';
import Lock from './svgs/Lock';
import LogIn from './svgs/LogIn';
import LogOut from './svgs/LogOut';
import Mail from './svgs/Mail';
import Map from './svgs/Map';
import MapPin from './svgs/MapPin';
import Maximize from './svgs/Maximize';
import Maximize2 from './svgs/Maximize2';
import Menu from './svgs/Menu';
import MessageCircle from './svgs/MessageCircle';
import MessageSquare from './svgs/MessageSquare';
import Mic from './svgs/Mic';
import MicOff from './svgs/MicOff';
import Minimize from './svgs/Minimize';
import Minimize2 from './svgs/Minimize2';
import Minus from './svgs/Minus';
import MinusCircle from './svgs/MinusCircle';
import MinusSquare from './svgs/MinusSquare';
import Monitor from './svgs/Monitor';
import Moon from './svgs/Moon';
import MoreHorizontal from './svgs/MoreHorizontal';
import MoreVertical from './svgs/MoreVertical';
import Move from './svgs/Move';
import Music from './svgs/Music';
import Navigation from './svgs/Navigation';
import Navigation2 from './svgs/Navigation2';
import Octagon from './svgs/Octagon';
import Package from './svgs/Package';
import Paperclip from './svgs/Paperclip';
import Pause from './svgs/Pause';
import PauseCircle from './svgs/PauseCircle';
import Percent from './svgs/Percent';
import Phone from './svgs/Phone';
import PhoneCall from './svgs/PhoneCall';
import PhoneForwarded from './svgs/PhoneForwarded';
import PhoneIncoming from './svgs/PhoneIncoming';
import PhoneMissed from './svgs/PhoneMissed';
import PhoneOff from './svgs/PhoneOff';
import PhoneOutgoing from './svgs/PhoneOutgoing';
import PieChart from './svgs/PieChart';
import Play from './svgs/Play';
import PlayCircle from './svgs/PlayCircle';
import Plus from './svgs/Plus';
import PlusCircle from './svgs/PlusCircle';
import PlusSquare from './svgs/PlusSquare';
import Pocket from './svgs/Pocket';
import Power from './svgs/Power';
import Printer from './svgs/Printer';
import Radio from './svgs/Radio';
import RefreshCcw from './svgs/RefreshCcw';
import RefreshCw from './svgs/RefreshCw';
import Repeat from './svgs/Repeat';
import Rewind from './svgs/Rewind';
import RotateCcw from './svgs/RotateCcw';
import RotateCw from './svgs/RotateCw';
import Rss from './svgs/Rss';
import Save from './svgs/Save';
import Scissors from './svgs/Scissors';
import Search from './svgs/Search';
import Send from './svgs/Send';
import Server from './svgs/Server';
import Settings from './svgs/Settings';
import Share from './svgs/Share';
import Share2 from './svgs/Share2';
import Shield from './svgs/Shield';
import ShieldOff from './svgs/ShieldOff';
import ShoppingBag from './svgs/ShoppingBag';
import ShoppingCart from './svgs/ShoppingCart';
import Shuffle from './svgs/Shuffle';
import Sidebar from './svgs/Sidebar';
import SkipBack from './svgs/SkipBack';
import SkipForward from './svgs/SkipForward';
import Slack from './svgs/Slack';
import Slash from './svgs/Slash';
import Sliders from './svgs/Sliders';
import Smartphone from './svgs/Smartphone';
import Speaker from './svgs/Speaker';
import Square from './svgs/Square';
import Star from './svgs/Star';
import StopCircle from './svgs/StopCircle';
import Sun from './svgs/Sun';
import Sunrise from './svgs/Sunrise';
import Sunset from './svgs/Sunset';
import Tablet from './svgs/Tablet';
import Tag from './svgs/Tag';
import Target from './svgs/Target';
import Terminal from './svgs/Terminal';
import Thermometer from './svgs/Thermometer';
import ThumbsDown from './svgs/ThumbsDown';
import ThumbsUp from './svgs/ThumbsUp';
import ToggleLeft from './svgs/ToggleLeft';
import ToggleRight from './svgs/ToggleRight';
import Trash from './svgs/Trash';
import Trash2 from './svgs/Trash2';
import TrendingDown from './svgs/TrendingDown';
import TrendingUp from './svgs/TrendingUp';
import Triangle from './svgs/Triangle';
import Truck from './svgs/Truck';
import Tv from './svgs/Tv';
import Twitter from './svgs/Twitter';
import Type from './svgs/Type';
import Umbrella from './svgs/Umbrella';
import Underline from './svgs/Underline';
import Unlock from './svgs/Unlock';
import Upload from './svgs/Upload';
import UploadCloud from './svgs/UploadCloud';
import User from './svgs/User';
import UserCheck from './svgs/UserCheck';
import UserMinus from './svgs/UserMinus';
import UserPlus from './svgs/UserPlus';
import UserX from './svgs/UserX';
import Users from './svgs/Users';
import Video from './svgs/Video';
import VideoOff from './svgs/VideoOff';
import Voicemail from './svgs/Voicemail';
import Volume from './svgs/Volume';
import Volume1 from './svgs/Volume1';
import Volume2 from './svgs/Volume2';
import VolumeX from './svgs/VolumeX';
import Watch from './svgs/Watch';
import Wifi from './svgs/Wifi';
import WifiOff from './svgs/WifiOff';
import Wind from './svgs/Wind';
import X from './svgs/X';
import XCircle from './svgs/XCircle';
import XSquare from './svgs/XSquare';
import Youtube from './svgs/Youtube';
import Zap from './svgs/Zap';
import ZapOff from './svgs/ZapOff';
import ZoomIn from './svgs/ZoomIn';
import ZoomOut from './svgs/ZoomOut';

const icons = {
    Activity,
    Airplay,
    AlertCircle,
    AlertOctagon,
    AlertTriangle,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Anchor,
    Aperture,
    Archive,
    ArrowDown,
    ArrowDownCircle,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftCircle,
    ArrowRight,
    ArrowRightCircle,
    ArrowUp,
    ArrowUpCircle,
    ArrowUpLeft,
    ArrowUpRight,
    AtSign,
    Award,
    BarChart,
    BarChart2,
    Battery,
    BatteryCharging,
    Bell,
    BellOff,
    Bluetooth,
    Bold,
    Book,
    BookOpen,
    Bookmark,
    Box,
    Briefcase,
    Calendar,
    Camera,
    CameraOff,
    Cast,
    Check,
    CheckCircle,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    Chrome,
    Circle,
    Clipboard,
    Clock,
    Cloud,
    CloudDrizzle,
    CloudLightning,
    CloudOff,
    CloudRain,
    CloudSnow,
    Code,
    Codepen,
    Command,
    Compass,
    Copy,
    CornerDownLeft,
    CornerDownRight,
    CornerLeftDown,
    CornerLeftUp,
    CornerRightDown,
    CornerRightUp,
    CornerUpLeft,
    CornerUpRight,
    Cpu,
    CreditCard,
    Crop,
    Crosshair,
    Database,
    Delete,
    Disc,
    DollarSign,
    Download,
    DownloadCloud,
    Droplet,
    Edit,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FastForward,
    Feather,
    File,
    FileMinus,
    FilePlus,
    FileText,
    Film,
    Filter,
    Flag,
    Folder,
    FolderMinus,
    FolderPlus,
    Gift,
    GitBranch,
    GitCommit,
    GitMerge,
    GitPullRequest,
    Github,
    Gitlab,
    Globe,
    Grid,
    HardDrive,
    Hash,
    Headphones,
    Heart,
    HelpCircle,
    Home,
    Image,
    Inbox,
    Info,
    Instagram,
    Italic,
    Layers,
    Layout,
    LifeBuoy,
    Link,
    Link2,
    Linkedin,
    List,
    Loader,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Maximize,
    Maximize2,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    MicOff,
    Minimize,
    Minimize2,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    Music,
    Navigation,
    Navigation2,
    Octagon,
    Package,
    Paperclip,
    Pause,
    PauseCircle,
    Percent,
    Phone,
    PhoneCall,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    PhoneOutgoing,
    PieChart,
    Play,
    PlayCircle,
    Plus,
    PlusCircle,
    PlusSquare,
    Pocket,
    Power,
    Printer,
    Radio,
    RefreshCcw,
    RefreshCw,
    Repeat,
    Rewind,
    RotateCcw,
    RotateCw,
    Rss,
    Save,
    Scissors,
    Search,
    Send,
    Server,
    Settings,
    Share,
    Share2,
    Shield,
    ShieldOff,
    ShoppingBag,
    ShoppingCart,
    Shuffle,
    Sidebar,
    SkipBack,
    SkipForward,
    Slack,
    Slash,
    Sliders,
    Smartphone,
    Speaker,
    Square,
    Star,
    StopCircle,
    Sun,
    Sunrise,
    Sunset,
    Tablet,
    Tag,
    Target,
    Terminal,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    ToggleLeft,
    ToggleRight,
    Trash,
    Trash2,
    TrendingDown,
    TrendingUp,
    Triangle,
    Truck,
    Tv,
    Twitter,
    Type,
    Umbrella,
    Underline,
    Unlock,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserMinus,
    UserPlus,
    UserX,
    Users,
    Video,
    VideoOff,
    Voicemail,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Watch,
    Wifi,
    WifiOff,
    Wind,
    X,
    XCircle,
    XSquare,
    Youtube,
    Zap,
    ZapOff,
    ZoomIn,
    ZoomOut,
};

export {
    icons as default,
    Activity,
    Airplay,
    AlertCircle,
    AlertOctagon,
    AlertTriangle,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Anchor,
    Aperture,
    Archive,
    ArrowDown,
    ArrowDownCircle,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftCircle,
    ArrowRight,
    ArrowRightCircle,
    ArrowUp,
    ArrowUpCircle,
    ArrowUpLeft,
    ArrowUpRight,
    AtSign,
    Award,
    BarChart,
    BarChart2,
    Battery,
    BatteryCharging,
    Bell,
    BellOff,
    Bluetooth,
    Bold,
    Book,
    BookOpen,
    Bookmark,
    Box,
    Briefcase,
    Calendar,
    Camera,
    CameraOff,
    Cast,
    Check,
    CheckCircle,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    Chrome,
    Circle,
    Clipboard,
    Clock,
    Cloud,
    CloudDrizzle,
    CloudLightning,
    CloudOff,
    CloudRain,
    CloudSnow,
    Code,
    Codepen,
    Command,
    Compass,
    Copy,
    CornerDownLeft,
    CornerDownRight,
    CornerLeftDown,
    CornerLeftUp,
    CornerRightDown,
    CornerRightUp,
    CornerUpLeft,
    CornerUpRight,
    Cpu,
    CreditCard,
    Crop,
    Crosshair,
    Database,
    Delete,
    Disc,
    DollarSign,
    Download,
    DownloadCloud,
    Droplet,
    Edit,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FastForward,
    Feather,
    File,
    FileMinus,
    FilePlus,
    FileText,
    Film,
    Filter,
    Flag,
    Folder,
    FolderMinus,
    FolderPlus,
    Gift,
    GitBranch,
    GitCommit,
    GitMerge,
    GitPullRequest,
    Github,
    Gitlab,
    Globe,
    Grid,
    HardDrive,
    Hash,
    Headphones,
    Heart,
    HelpCircle,
    Home,
    Image,
    Inbox,
    Info,
    Instagram,
    Italic,
    Layers,
    Layout,
    LifeBuoy,
    Link,
    Link2,
    Linkedin,
    List,
    Loader,
    Lock,
    LogIn,
    LogOut,
    Mail,
    Map,
    MapPin,
    Maximize,
    Maximize2,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    MicOff,
    Minimize,
    Minimize2,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    Move,
    Music,
    Navigation,
    Navigation2,
    Octagon,
    Package,
    Paperclip,
    Pause,
    PauseCircle,
    Percent,
    Phone,
    PhoneCall,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    PhoneOutgoing,
    PieChart,
    Play,
    PlayCircle,
    Plus,
    PlusCircle,
    PlusSquare,
    Pocket,
    Power,
    Printer,
    Radio,
    RefreshCcw,
    RefreshCw,
    Repeat,
    Rewind,
    RotateCcw,
    RotateCw,
    Rss,
    Save,
    Scissors,
    Search,
    Send,
    Server,
    Settings,
    Share,
    Share2,
    Shield,
    ShieldOff,
    ShoppingBag,
    ShoppingCart,
    Shuffle,
    Sidebar,
    SkipBack,
    SkipForward,
    Slack,
    Slash,
    Sliders,
    Smartphone,
    Speaker,
    Square,
    Star,
    StopCircle,
    Sun,
    Sunrise,
    Sunset,
    Tablet,
    Tag,
    Target,
    Terminal,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    ToggleLeft,
    ToggleRight,
    Trash,
    Trash2,
    TrendingDown,
    TrendingUp,
    Triangle,
    Truck,
    Tv,
    Twitter,
    Type,
    Umbrella,
    Underline,
    Unlock,
    Upload,
    UploadCloud,
    User,
    UserCheck,
    UserMinus,
    UserPlus,
    UserX,
    Users,
    Video,
    VideoOff,
    Voicemail,
    Volume,
    Volume1,
    Volume2,
    VolumeX,
    Watch,
    Wifi,
    WifiOff,
    Wind,
    X,
    XCircle,
    XSquare,
    Youtube,
    Zap,
    ZapOff,
    ZoomIn,
    ZoomOut,
};
