const contextMode = () => {
    if (
        process.env.NODE_ENV !== 'development' ||
        process.env.LAZY_GET_COMPONENTS === 'on'
    ) {
        return 'lazy-once';
    }

    return 'sync';
};

/**
 * Use liberally for additional core configuration.
 * @type {Object}
 */
module.exports = {
    version: '3.0.9',
    semver: '^3.0.0',
    update: {
        package: {
            devDependencies: {
                add: {
                    'gulp-run': '^1.7.1',
                    'atomic-reactor-cli': '^2.1.4',
                    'babel-core': '^7.0.0-bridge.0',
                    'babel-jest': '^24.8.0',
                    '@babel/core': '^7.4.5',
                    '@babel/preset-env': '^7.4.5',
                    '@babel/preset-react': '^7.0.0',
                    '@babel/plugin-proposal-class-properties': '^7.4.4',
                    '@babel/plugin-proposal-export-default-from': '^7.2.0',
                    '@babel/plugin-syntax-dynamic-import': '^7.2.0',
                    'babel-loader': '^8.0.6',
                    'browser-sync': '^2.26.7',
                    camelcase: '^5.0.0',
                    'compression-webpack-plugin': '^2.0.0',
                    'cli-spinners': '^1.3.1',
                    decamelize: '^2.0.0',
                    enzyme: '^3.8.0',
                    'enzyme-adapter-react-16': '^1.13.2',
                    'fast-diff': '^1.2.0',
                    'fs-extra': '^7.0.1',
                    'fs-readdir-recursive': '^1.1.0',
                    gulp: '^4.0.2',
                    'gulp-autoprefixer': '^6.1.0',
                    'gulp-clean-css': '^4.2.0',
                    'gulp4-run-sequence': '^0.3.3',
                    'gulp-sourcemaps': '^2.6.5',
                    'gulp-clean-css': '^4.0.0',
                    'gulp-gzip': '^1.4.2',
                    handlebars: '^4.1.2',
                    jest: '^24.8.0',
                    'module-alias': '^2.1.0',
                    'node-sass': '^4.12.0',
                    'node-sass-functions-json': '^1.0.0',
                    'node-sass-tilde-importer': '^1.0.2',
                    nodemon: '^1.19.1',
                    ora: '^3.0.0',
                    slugify: '^1.3.4',
                    webpack: '^4.32.2',
                    'webpack-dev-middleware': '^3.7.0',
                    'webpack-filter-warnings-plugin': '^1.2.1',
                    'webpack-hot-middleware': '^2.25.0',
                    eslint: '^5.12.0',
                    'eslint-plugin-react': '^7.13.0',
                    'eslint-plugin-react-hooks': '^1.5.1',
                    'babel-eslint': '^10.0.1',
                    stylelint: '^9.10.1',
                },
                remove: [
                    'atomic-reactor-cli',
                    'babel-cli',
                    'babel-core',
                    '@babel/core',
                    '@babel/plugin-proposal-class-properties',
                    '@babel/plugin-syntax-dynamic-import',
                    'babel-jest',
                    'babel-loader',
                    'babel-preset-env',
                    '@babel/preset-env',
                    'babel-preset-react',
                    'babel-preset-stage-2',
                    'browser-sync',
                    'enzyme-adapter-react-16',
                    'eslint-plugin-react',
                    'gulp',
                    'gulp-autoprefixer',
                    'gulp-clean-css',
                    'gulp-install',
                    'gulp-sourcemaps',
                    'gulp4-run-sequence',
                    'gulp-csso',
                    'handlebars',
                    'jest',
                    'node-sass',
                    'nodemon',
                    'run-sequence',
                    'slugify',
                    'vinyl-source-stream',
                    'webpack',
                    'webpack-dev-middleware',
                    'webpack-filter-warnings-plugin',
                    'webpack-hot-middleware',
                    'webpack-visualizer-plugin',
                ],
            },
            dependencies: {
                add: {
                    '@babel/cli': '^7.4.4',
                    '@babel/node': '^7.4.5',
                    '@babel/polyfill': '^7.4.4',
                    axios: '^0.19.0',
                    classnames: '^2.2.6',
                    'cookie-parser': '^1.4.4',
                    'copy-to-clipboard': '^3.2.0',
                    'core-js': '^2.6.9',
                    cors: '^2.8.5',
                    'directory-tree': '^2.2.3',
                    eslint: '^5.16.0',
                    express: '^4.17.1',
                    'express-static-gzip': '^1.1.3',
                    globby: '^9.2.0',
                    gsap: '^2.1.3',
                    'http-proxy-middleware': '^0.19.1',
                    marked: '^0.6.1',
                    moment: '^2.24.0',
                    prettier: '^1.15.1',
                    'prop-types': '^15.7.2',
                    react: '^16.8.6',
                    'react-dom': '^16.8.6',
                    'react-frame-component': '^4.1.0',
                    'react-helmet': '^5.2.1',
                    'react-redux': '^7.0.3',
                    'react-router-config': '^5.0.0',
                    'react-router-dom': '^5.0.0',
                    'react-syntax-highlighter': '^10.3.0',
                    'redbox-react': '^1.6.0',
                    redux: '4.0.1',
                    'redux-devtools': '^3.5.0',
                    'redux-local-persist': '0.1.0',
                    'redux-super-thunk': '^0.0.7',
                    'run-script-os': '^1.0.5',
                    'shallow-equals': '^1.0.0',
                    xss: '^1.0.3',
                },
                remove: [
                    'ajv',
                    'axios',
                    '@babel/cli',
                    '@babel/node',
                    '@babel/polyfill',
                    '@babel/plugin-syntax-dynamic-import',
                    'beautify',
                    'cookie-parser',
                    'copy-to-clipboard',
                    'core-js',
                    'cors',
                    'directory-tree',
                    'eslint',
                    'express',
                    'express-http-proxy',
                    'globby',
                    'gsap',
                    'htmltojsx',
                    'js-beautify',
                    'marked',
                    'moment',
                    'prop-types',
                    'react',
                    'react-dom',
                    'react-frame-component',
                    'react-helmet',
                    'react-redux',
                    'react-router-config',
                    'react-router-dom',
                    'react-syntax-highlighter',
                    'redux',
                    'redux-local-persist',
                ],
            },
            scripts: {
                add: {
                    build: 'npm-run-all build:*',
                    static: 'npm-run-all build:* && gulp static',
                    local: 'gulp local',
                    'local:ssr': 'gulp local:ssr',
                },
                remove: [
                    'build:cleanup',
                    'local-fe-start',
                    'local-fe:gulp',
                    'local-fe:babel-node',
                    'local-ssr-start',
                    'local-ssr:gulp',
                    'local-ssr:babel-node',
                    'react-redux',
                    'static:build',
                ],
            },
        },
        files: {
            add: [
                {
                    overwrite: true,
                    version: '>=3.0.0',
                    destination: '/Dockerfile',
                    source: '/tmp/update/Dockerfile',
                },
                {
                    overwrite: true,
                    version: '>=2.3.16',
                    destination: '/src/app/plugable',
                    source: '/tmp/update/src/app/plugable',
                },
                {
                    overwrite: false,
                    version: '>=2.3.16',
                    destination: '.stylelintrc',
                    source: '/tmp/update/.stylelintrc',
                },
                {
                    overwrite: false,
                    version: '>=2.3.16',
                    destination:
                        '/src/app/components/common-ui/Icon/defaultProps.js',
                    source:
                        '/tmp/update/src/app/components/common-ui/Icon/defaultProps.js',
                },
                {
                    overwrite: false,
                    version: '>=2.3.16',
                    destination: '/src/app/components/common-ui/Icon/index.js',
                    source:
                        '/tmp/update/src/app/components/common-ui/Icon/index.js',
                },
                {
                    overwrite: true,
                    version: '>=2.3.16',
                    destination: '/src/app/components/common-ui/Icon/Feather',
                    source:
                        '/tmp/update/src/app/components/common-ui/Icon/Feather',
                },
                {
                    overwrite: true,
                    version: '>=2.3.16',
                    destination: '/src/app/toolkit/icons/Feather',
                    source: '/tmp/update/src/app/toolkit/icons/Feather',
                },
                {
                    overwrite: true,
                    version: '>=3.0.2',
                    destination: '/.eslintrc',
                    source: '/tmp/update/.eslintrc',
                },
                {
                    overwrite: false,
                    version: '>=3.0.3',
                    destination: '/src/app/components/Fallback',
                    source: '/tmp/update/src/app/components/Fallback',
                },
            ],
            remove: [],
        },
    },
    manifest: {
        patterns: [
            {
                name: 'allActions',
                type: 'actions',
                pattern: /actions.jsx?$/,
            },
            {
                name: 'allActionTypes',
                type: 'actionTypes',
                pattern: /actionTypes.jsx?$/,
            },
            {
                name: 'allReducers',
                type: 'reducers',
                pattern: /reducers.jsx?$/,
            },
            {
                name: 'allInitialStates',
                type: 'state',
                pattern: /state.jsx?$/,
            },
            {
                name: 'allRoutes',
                type: 'route',
                pattern: /route.jsx?$/,
            },
            {
                name: 'allServices',
                type: 'services',
                pattern: /services.jsx?$/,
            },
            {
                name: 'allMiddleware',
                type: 'middleware',
                pattern: /middleware.jsx?$/,
                ignore: /server\/middleware/,
            },
            {
                name: 'allEnhancers',
                type: 'enhancer',
                pattern: /enhancer.jsx?$/,
            },
            {
                name: 'allPlugins',
                type: 'plugin',
                pattern: /plugin.jsx?$/,
            },
        ],
        sourceMappings: [
            {
                from: 'src/app/',
                to: '',
            },
            {
                from: '.core/',
                to: 'reactium-core/',
            },
        ],
        contexts: {
            components: {
                modulePath: 'components',
                filePattern: '.js?$',
                mode: contextMode(),
            },
            common: {
                modulePath: 'components/common-ui/',
                filePattern: '.js?$',
                mode: contextMode(),
            },
            toolkit: {
                modulePath: 'toolkit',
                filePattern: '.js?$',
                mode: contextMode(),
            },
            core: {
                modulePath: 'reactium-core/components',
                filePattern: '.js?$',
                mode: contextMode(),
            },
        },
    },
};
