export default {
    TOOLKIT_MOUNT: 'TOOLKIT_MOUNT',
    TOOLKIT_LOAD: 'TOOLKIT_LOAD',
    TOOLKIT_LOADED: 'TOOLKIT_LOADED',
    TOOLKIT_NAV: 'TOOLKIT_NAV',
    TOOLKIT_PREF: 'TOOLKIT_PREF',
    TOOLKIT_THEME: 'TOOLKIT_THEME',
    TOOLKIT_MENU_TOGGLE: 'TOOLKIT_MENU_TOGGLE',
    TOOLKIT_NOTICE_TOGGLE: 'TOOLKIT_NOTICE_TOGGLE',
    TOOLKIT_NOTICE_UPDATE: 'TOOLKIT_NOTICE_UPDATE',
    TOOLKIT_SETTINGS_TOGGLE: 'TOOLKIT_SETTINGS_TOGGLE',
};
