const path = require('path');
const chalk = require('chalk');
const fs = require('fs-extra');
const _ = require('underscore');
const op = require('object-path');
const prettier = require('prettier');
const globby = require('globby');

module.exports = spinner => {
    const message = text => {
        if (spinner) {
            spinner.text = text;
        }
    };

    const results = { scan: [] };

    const scan = ({ action, params, props }) => {
        message(`Scanning for ${chalk.cyan('zones')}. This may take awhile...`);

        const { cwd = process.cwd() } = props;
        const globs = [path.normalize(`${cwd}/src/**/*.js*`)];

        if (op.get(params, 'node') === true) {
            globs.push(path.normalize(`${cwd}/node_modules/**/*.js*`));
        }

        const quick_scan = /\<Plugins/;

        return globby(globs).then(files => {
            const zones = files.reduce((z, file) => {
                const contents = fs.readFileSync(file);
                if (!quick_scan.test(contents)) {
                    return z;
                }

                const reg_find = /<Plugins[\s\S](.*?)[\s\S]\/>/g;
                const match = reg_find.exec(
                    String(fs.readFileSync(file)).replace(/["'\s+]/g, ' '),
                );

                if (match) {
                    const zone = String(match[0]).match(/zone= (.*?) /i);
                    if (Array.isArray(zone) && zone.length > 1) {
                        z.push({
                            zone: zone[1],
                            file: file.replace(path.normalize(cwd), ''),
                        });
                    }
                }

                return z;
            }, []);

            if (action) {
                results[action] = zones;
            }

            return { action, status: 200, zones };
        });
    };

    const save = ({ action, params, props }) => {
        message(`Saving ${chalk.cyan('plugin-zones.js')}...`);

        const { cwd = process.cwd() } = props;
        const output = `
        // File generated by $ arcli <zone> command
        // DONOT directly edit !!!!!\n\n

        module.exports = {
            get: () => {
                return ${JSON.stringify(results.scan)};
            },
        };
        `;
        const cont = prettier.format(output, {
            parser: 'babylon',
        });

        const filePath = path.normalize(`${cwd}/.core/plugin-zones.js`);
        fs.ensureFileSync(filePath);
        fs.writeFileSync(filePath, cont);

        return Promise.resolve({ action, status: 200 });
    };

    return {
        scan,
        save,
    };
};
